### ISSUE TITLE
Exception with x64 version

### ISSUE THREAD

**Issue by chcg** [pnedev/compare-plugin#133] opened 2017-07-02 08:23 UTC
Hi,

I got this exception with x64 compare plugin 2.0.0. Happened just once, not reproducable yet. Comparision of two xml files.

Ausnahmefehler bei 0x00007ffb158b1d83 (ComparePlugin.dll) in notepad++.exe: 0xC000041D: Ausnahmefehler während eines Benutzerrückrufs.

Callstack:
```

>	ComparePlugin.dll!setInfo()  + 0x6c63 Bytes	
 	[Unten angegebene Rahmen sind möglicherweise nicht korrekt und/oder fehlen, keine Symbole geladen für ComparePlugin.dll]	
 	ComparePlugin.dll!setInfo()  + 0x7e9e Bytes	
 	ComparePlugin.dll!setInfo()  + 0x64aa Bytes	
 	ComparePlugin.dll!setInfo()  + 0x796c Bytes	
 	ComparePlugin.dll!setInfo()  + 0x9fc8 Bytes	
 	user32.dll!UserCallDlgProcCheckWow()  + 0xfe Bytes	
 	user32.dll!DefDlgProcWorker()  + 0xd1 Bytes	
 	user32.dll!DefDlgProcW()  + 0x36 Bytes	
 	user32.dll!UserCallWinProcCheckWow()  + 0x280 Bytes	
 	user32.dll!DispatchClientMessage()  + 0x9c Bytes	
 	user32.dll!__fnDWORD()  + 0x33 Bytes	
 	ntdll.dll!KiUserCallbackDispatcherContinue() 	
 	win32u.dll!NtUserMessageCall()  + 0x14 Bytes	
 	user32.dll!SendMessageWorker()  + 0x120 Bytes	
 	user32.dll!RealDefWindowProcWorker()  + 0x341 Bytes	
 	user32.dll!RealDefWindowProcW()  + 0x52 Bytes	
 	uxtheme.dll!_ThemeDefWindowProc(HWND__ * hwnd, unsigned int uMsg, unsigned __int64 wParam, __int64 lParam, int bUnicode)  Zeile 1090	C++
 	uxtheme.dll!ThemeDefWindowProcW(HWND__ * hwnd, unsigned int uMsg, unsigned __int64 wParam, __int64 lParam)  Zeile 1104	C++
 	user32.dll!DefWindowProcW()  + 0x1b7 Bytes	
 	user32.dll!DefDlgProcWorker()  + 0x1bf Bytes	
 	user32.dll!DefDlgProcW()  + 0x36 Bytes	
 	user32.dll!UserCallWinProcCheckWow()  + 0x280 Bytes	
 	user32.dll!DispatchClientMessage()  + 0x9c Bytes	
 	user32.dll!__fnINLPWINDOWPOS()  + 0x30 Bytes	
 	ntdll.dll!KiUserCallbackDispatcherContinue() 	
 	win32u.dll!NtUserSetWindowPos()  + 0x14 Bytes	
 	notepad++.exe!00007ff6fdae3a48() 	
 	notepad++.exe!00007ff6fdae459b() 	
 	notepad++.exe!00007ff6fdb99268() 	
 	user32.dll!UserCallDlgProcCheckWow()  + 0xfe Bytes	
 	user32.dll!DefDlgProcWorker()  + 0xd1 Bytes	
 	user32.dll!DefDlgProcW()  + 0x36 Bytes	
 	user32.dll!UserCallWinProcCheckWow()  + 0x280 Bytes	
 	user32.dll!DispatchClientMessage()  + 0x9c Bytes	
 	user32.dll!__fnDWORD()  + 0x33 Bytes	
 	ntdll.dll!KiUserCallbackDispatcherContinue() 	
 	win32u.dll!NtUserMessageCall()  + 0x14 Bytes	
 	user32.dll!SendMessageWorker()  + 0x120 Bytes	
 	user32.dll!RealDefWindowProcWorker()  + 0x341 Bytes	
 	user32.dll!RealDefWindowProcW()  + 0x52 Bytes	
 	uxtheme.dll!_ThemeDefWindowProc(HWND__ * hwnd, unsigned int uMsg, unsigned __int64 wParam, __int64 lParam, int bUnicode)  Zeile 1090	C++
 	uxtheme.dll!ThemeDefWindowProcW(HWND__ * hwnd, unsigned int uMsg, unsigned __int64 wParam, __int64 lParam)  Zeile 1104	C++
 	user32.dll!DefWindowProcW()  + 0x1b7 Bytes	
 	user32.dll!DefDlgProcWorker()  + 0x1bf Bytes	
 	user32.dll!DefDlgProcW()  + 0x36 Bytes	
 	user32.dll!UserCallWinProcCheckWow()  + 0x280 Bytes	
 	user32.dll!DispatchClientMessage()  + 0x9c Bytes	
 	user32.dll!__fnINLPWINDOWPOS()  + 0x30 Bytes	
 	ntdll.dll!KiUserCallbackDispatcherContinue() 	
 	win32u.dll!NtUserSetWindowPos()  + 0x14 Bytes	
 	notepad++.exe!00007ff6fdae61b7() 	
 	notepad++.exe!00007ff6fdb2ea05() 	
 	notepad++.exe!00007ff6fdb32837() 	
 	notepad++.exe!00007ff6fdb2e561() 	
 	user32.dll!UserCallWinProcCheckWow()  + 0x280 Bytes	
 	user32.dll!DispatchClientMessage()  + 0x9c Bytes	
 	user32.dll!__fnDWORD()  + 0x33 Bytes	
 	ntdll.dll!KiUserCallbackDispatcherContinue() 	
 	win32u.dll!NtUserMessageCall()  + 0x14 Bytes	
 	user32.dll!SendMessageWorker()  + 0x120 Bytes	
 	user32.dll!RealDefWindowProcWorker()  + 0x341 Bytes	
 	user32.dll!RealDefWindowProcW()  + 0x52 Bytes	
 	uxtheme.dll!_ThemeDefWindowProc(HWND__ * hwnd, unsigned int uMsg, unsigned __int64 wParam, __int64 lParam, int bUnicode)  Zeile 1090	C++
 	uxtheme.dll!ThemeDefWindowProcW(HWND__ * hwnd, unsigned int uMsg, unsigned __int64 wParam, __int64 lParam)  Zeile 1104	C++
 	user32.dll!DefWindowProcW()  + 0x1b7 Bytes	
 	notepad++.exe!00007ff6fdb2e8d4() 	
 	notepad++.exe!00007ff6fdb32837() 	
 	notepad++.exe!00007ff6fdb2e561() 	
 	user32.dll!UserCallWinProcCheckWow()  + 0x280 Bytes	
 	user32.dll!DispatchClientMessage()  + 0x9c Bytes	
 	user32.dll!__fnINLPWINDOWPOS()  + 0x30 Bytes	
 	ntdll.dll!KiUserCallbackDispatcherContinue() 	
 	win32u.dll!NtUserMessageCall()  + 0x14 Bytes	
 	user32.dll!RealDefWindowProcWorker()  + 0x1ba Bytes	
 	user32.dll!RealDefWindowProcW()  + 0x52 Bytes	
 	uxtheme.dll!DoMsgDefault(const _THEME_MSG * ptm)  Zeile 550	C++
 	uxtheme.dll!OnDwpSysCommand(CThemeWnd * pwnd, _THEME_MSG * ptm)  Zeile 7636	C++
 	uxtheme.dll!_ThemeDefWindowProc(HWND__ * hwnd, unsigned int uMsg, unsigned __int64 wParam, __int64 lParam, int bUnicode)  Zeile 1060 + 0x49 Bytes	C++
 	uxtheme.dll!ThemeDefWindowProcW(HWND__ * hwnd, unsigned int uMsg, unsigned __int64 wParam, __int64 lParam)  Zeile 1104	C++
 	user32.dll!DefWindowProcW()  + 0x1b7 Bytes	
 	notepad++.exe!00007ff6fdb2f17c() 	
 	notepad++.exe!00007ff6fdb32837() 	
 	notepad++.exe!00007ff6fdb2e561() 	
 	user32.dll!UserCallWinProcCheckWow()  + 0x280 Bytes	
 	user32.dll!DispatchMessageWorker()  + 0x19f Bytes	
 	notepad++.exe!00007ff6fdbbe81e() 	
 	notepad++.exe!00007ff6fdbcc01c() 	
 	kernel32.dll!BaseThreadInitThunk()  + 0x14 Bytes	
 	ntdll.dll!RtlUserThreadStart()  + 0x21 Bytes	


```

Info:

Notepad++ v7.4.2   (64-bit)
Build time : Jun 18 2017 - 23:38:43
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppFTP.dll PluginManager.dll XMLTools.dll

**Comment by pnedev** [comment] 2017-07-04 07:21
Hi,

I'll investigate the issue,
Thanks for the report and the debug info.

BR

**Comment by MKaveh** [comment] 2017-07-22 12:04
I also have this problem recently; using latest 64-bit version of Notepad++.
I wanted to compare two .csv files, while in compare mode, when I wanted to save one of the files or when clicking Compare>Clear all compares:
an error message dialog was displayed several time: 
	Exception:   Unkown Exception

**Comment by pnedev** [comment] 2017-07-24 08:52
Hi @MKaveh ,

Thank you for the report.

Is the issue consistently reproducible on your side?

BR

**Comment by MKaveh** [comment] 2017-08-27 12:23
No, It seems that it was fixed later after a clean installation of
Notepad++.

2017-07-24 13:22 GMT+04:30 Pavel Nedev <notifications@github.com>:

**Comment by pnedev** [comment] 2017-10-18 14:44
Hello @chcg ,

I did some research on the error code you reported and it appears that the cause might be connected with the keyboard hook procedure used by the progress dialog.
I made some changes to the code accordingly but nevertheless I cannot be sure the issue is fixed as it is not steadily reproducable.
I'll close this thread now but if you experience the issue again please write back.
Thanks.

BR

**Closed by pnedev** 2017-10-18 14:44 UTC
Labels: bug

**Comment by chcg** [comment] 2017-10-18 16:29
Haven't seen the issue again since reporting it. So I'm fine with closing it. Thanks for your investigation.
