### ISSUE TITLE
Plugin crashes on NP++

### ISSUE THREAD

**Issue by ten2120** [pnedev/compare-plugin#287] opened 2022-05-23 18:31 UTC
Hi there,
ComparePlugin v2.0.2 (x64) crashes on NP++ v8.4.1 Minimal Portable version (I had no issue with previous versions).

Debug Info:
Notepad++ v8.4.1 (64-bit)
Build time : May 8 2022 - 19:51:18
Path : D:\Notepad\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 (64-bit)
OS Version : 2009
OS Build : 22000.652
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll

Recorded video (crash process!):
https://mega.nz/file/JxgVgZyK#d5bYUIWu8qHTEXxsHdH5px4PNMf1_IzbiLI0BkivNCs

**Comment by pnedev** [comment] 2022-05-24 20:39
Hi @ten2120 ,

I did a quick test with Notepad++ 8.4.1 64-bit (the installable version) under Windows 10 and everything worked normal.
Could you tell me where you got the Compare plugin 2.0.2 from?
Is there a chance you can try on Windows 10 computer? I have never tested Compare on Windows 11.

BR

**Comment by rdipardo** [comment] 2022-05-25 03:24
Cannot reproduce using 8.4.1 portable on Windows 11 (Home edition) and Compare 2.0.2 (installed via Plugins Admin).

![compare_202_npp_8 4 1_x86_64](https://user-images.githubusercontent.com/59004801/170171613-ba60b8f6-0451-4b61-bf80-4d10160c96ca.png)

    Notepad++ v8.4.1   (64-bit)
    Build time : May  8 2022 - 19:51:18
    Path : C:\Users\Rob\git\npp_8.4.1_x86_64\notepad++.exe
    Command Line : 
    Admin mode : OFF
    Local Conf mode : ON
    Cloud Config : OFF
    OS Name : Windows 11 (64-bit) 
    OS Version : 2009
    OS Build : 22000.706
    Current ANSI codepage : 1252
    Plugins : ComparePlugin.dll

**Comment by pnedev** [comment] 2022-05-25 10:42
@rdipardo ,

Thank you very much for testing and reporting! :+1: 

@ten2120 ,

How and where from have you installed Compare plugin?

**Comment by pnedev** [comment] 2022-05-26 07:37
@ten2120 ,

I just tried Notepad++ 8.4.1 portable minimal 64-bit (https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.4.1/npp.8.4.1.portable.minimalist.x64.7z) with Compare plugin 2.0.2 64-bit from my releases (https://github.com/pnedev/compare-plugin/releases/download/v2.0.2/ComparePlugin_v2.0.2_X64.zip) and it worked OK.
Your plugin path is the same as mine. The only difference I see is that I tested on Windows10 and you had the issue on Win11 and unfortunately I do not have Win11 Enterprise environment.
So at the moment I cannot help you any further. I may only suggest you to try Notepad++ portable (but not minimal) or maybe install the 64-bit version (if you can) and maybe use Plugins Admin to download Compare plugin.

**Comment by ten2120** [comment] 2022-05-26 09:30
@pnedev Many thanks for your help. I compare my txt files with "Word" (it is just more complicated with MS Word). I hope this problem be solved in future (your plugin was a great assistant for me, thanks for it!).

**Comment by monolied** [comment] 2022-05-30 12:58
2.0.2 also crashes on my Notepad++ 8.4.1 portable under Win 10.

```
Notepad++ v8.4.1   (64-bit)
Build time : May  8 2022 - 19:51:18
Path : C:\Users\Name\_Daten\PortableApps\PortableApps\Notepad++Portable\App\Notepad++64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : C:\Users\Name\_Daten\PortableApps\PortableApps\Notepad++Portable\Data\Config
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1586
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll 
```

**Comment by monolied** [comment] 2022-05-30 13:17
Hm, I just installed 2.0.2 manually (in ComparePlugin folder), without Plugin Manager, and now it seems to work. Maybe Plugin Manager was unable to fetch 2.0.2 or there was some irritation with ComparePlus/ComparePlugin?

**Comment by monolied** [comment] 2022-06-02 11:45
> In your first post I don't see the Compare plugin in your plugins list.

That's true. Like I wrote, it disappeared from the plugin list every time after the crash and restart. It reappeared after an install via the Plugin Manager or a manual reinstall.

I'd also consider the matter closed as far as I'm concerned. Since the Plugin Manager seems to fail to install the 2.0.2 plugin (it _looked_ like success, but must have been the old one still) it seems to be a problem with the Plugin Manager in my case. It might well be in other cases, too, but in the OPs case, it might not, since he also insatalled manually.

**Comment by pnedev** [comment] 2022-06-02 11:57
@monolied ,

Yes, I agree with you. It might be related to Plugin Manager's issue but for @ten2120 that's not the case.
Thanks for writing.

**Comment by pnedev** [comment] 2022-06-02 12:01
@ten2120 ,

Just a quick question.
Have you changed any settings of the ComparePlugin before the crash (that is any settable options of the plugin from its menu section) ?
Thanks.

**Comment by pnedev** [comment] 2022-07-17 12:37
@ten2120 ,

In a month I will release the first version of ComparePlus. It will be available for more recent versions of Notepad++ (maybe from v8.4.1 and up but not sure as I have no idea if there will not be more core changes in newer Notepad++ versions that will require compatibility fixes). You will be able to get it through PluginsAdmin.
I will close this thread now as I cannot reproduce it and it is probably related to compatibility issues. Please try later with ComparePlus when it is out and create another report here if you have problems again.
Thanks for your cooperation.

BR

**Closed by pnedev** 2022-07-17 12:37 UTC
Labels: question

**Comment by Squall-Leonhart** [comment] 2023-08-27 07:35
This crash occurs when comparing two files with many lines (tens of thousands), the same files can be compared fine with Total commander, TortoiseDiff, etc.

**Comment by pnedev** [comment] 2023-08-27 21:27
@Squall-Leonhart ,
Could you be more specific please?
What is your Notepad++ version, what version of the plugin are you using and do you have other plugins as well?
How exactly this "crash" looks like?
If it is possible for you to provide the files for testing that will also be of great help.
Thank you.

**Comment by ten2120** [comment] 2023-09-23 18:28
It works (version below, x64):
https://github.com/pnedev/comparePlus/releases/download/cp_1.1.0/ComparePlus_cp_1.1.0_x64.zip

My NP++ version: 8.5.7 minimal portable.
Many thanks @pnedev 👍🏻
