### ISSUE TITLE
Compare Plugin Bug 

### ISSUE THREAD

**Issue by Teubert1162** [pnedev/compare-plugin#100] opened 2016-10-13 16:46 UTC
When Comparing the two files the "", \\, and Nums move. If I compare again the characters that moved are deleted. 

![io compare](https://cloud.githubusercontent.com/assets/22820859/19358132/bdbc7194-9142-11e6-880b-84803b5ca1f5.png)

**Comment by pnedev** [comment] 2016-10-14 08:46
Hello,

CP version 1.5.6 is rather old. I've made a lot of changes and I'm close to releasing a new version soon.
Could you please re-test with the latest development version just to be sure the issue is still present?
Here is a link to it:
https://ci.appveyor.com/api/buildjobs/3hgxkq2ghtm46jr9/artifacts/ComparePlugin.Win32.Release%20Unicode.v120_xp.dll

Thanks.

BR

**Comment by Teubert1162** [comment] 2016-10-14 14:36
I've loaded in the development version and tested. That looks like it fixed
it. I'll test a few more files to be sure but looks like its working
correctly.

Thanks

Mike T

**Comment by pnedev** [comment] 2016-10-14 22:12
OK, I'm closing this issue then.
If you find something similar in the future I'll re-open it.
Thanks.

BR

**Closed by pnedev** 2016-10-14 22:12 UTC
Labels: question

**Comment by Yaron10** [comment] 2016-10-14 22:30
Hello Pavel and Teubert1162,

@Pavel,
Great. :)

@Teubert1162,
Could you please mention in the NPP Forum that the problem is fixed in Pavel's version?

Best regards.
