### ISSUE TITLE
A problem with the text lines.

### ISSUE THREAD

**Issue by davidtuning** [pnedev/compare-plugin#111] opened 2017-02-16 05:45 UTC
When I select some text with the compare option activate, the lines in the old file get back and is impossible to edit or view if I put the cursor in the end of the line is get back.
This work normaly in the old version. 
http://puu.sh/u5lxS/1ee02816f2.png
http://puu.sh/u5lyY/a4d681ae8a.png

**Comment by pnedev** [comment] 2017-02-16 07:52
I don't quite understand the problem. Could you give exact steps to reproduce the case and what do you expect the behavior to be?

In the new version, when you move the cursor in one of the files and the line is changed, the cursor in the other file is positioned on the same line number. This is done for alignment purposes. If you have selection the line (and the selection) is not changed - the cursor is not re-positioned.

**Comment by pnedev** [comment] 2017-02-20 13:11
@davidtuning ,
Would you explain the problem in more details or is it OK with you?

**Comment by davidtuning** [comment] 2017-02-20 20:17
Sorry, I was have a few days without electrical suministry. 
The problem is the when I select one line in the old compared file the hole text is scroll to the left and I'cant edit or select correctly the lines, but in the comparaded new one the is no problem I can select or edit without problem.

**Comment by davidtuning** [comment] 2017-02-20 22:36
Here is a video of what I tried to say. https://youtu.be/3MEKtdCVEVA

**Comment by pnedev** [comment] 2017-02-21 08:32
@davidtuning , thanks for the video, not the problem is visible.
I'll have a look at write back.

**Comment by pnedev** [comment] 2017-02-21 15:54
@davidtuning ,
The problem is fixed with commit https://github.com/pnedev/compare-plugin/commit/e9e9ef14e763a701f01ef816f9cf4f6d22f63e39.

The binaries are as follow:

- x64:  https://ci.appveyor.com/api/buildjobs/3n82tyq5to6ui8bi/artifacts/ComparePlugin.dll
- x86:  https://ci.appveyor.com/api/buildjobs/6hgfxkay2c2uwm9h/artifacts/ComparePlugin.dll

Please note that this is a development version that has some new features / fixes that are not officially released yet.
Test and write back if you still observe some issues.

**Comment by Yaron10** [comment] 2017-02-21 21:41
Hello Pavel,

This time I should compliment you more for understanding the issue rather than for fixing it. :)
Thank you.

BR

**Comment by davidtuning** [comment] 2017-02-21 22:54
Yeah, is working fine now, but the navigation bar is not show up when I select it.
And thanks for fixing this, I really appreciate it.

**Comment by pnedev** [comment] 2017-02-22 08:50
Hello @Yaron10 ,

Thanks.

Hello @davidtuning ,

Please go to your Notepad++ plugins config folder and delete the _ComparePlugin.ini_ file to clear the config discrepancies that might appear due to the new CP development version. Then start N++ and configure again CP to your liking.

BR

**Closed by pnedev** 2017-02-22 08:50 UTC
Labels: bug

**Comment by davidtuning** [comment] 2017-02-22 15:05
Mmm, I delete the file (from: *AppData\Roaming\Notepad++\plugins\config) and the icons stil duplicate.

**Comment by pnedev** [comment] 2017-02-22 15:20
Hm, do you have the _Customize Toolbar_ plugin installed?
If yes, please try disabling it temporarily (move the _CustomizeToolbar.dll_ from _plugins_ to _plugins/disabled_ folder) and try again.

**Comment by davidtuning** [comment] 2017-02-22 15:23
Yeah, was that, the plugin don't remove the old ones so I reset the icons and is working fine now, thanks again.

**Comment by pnedev** [comment] 2017-02-22 15:25
Great,
BR

**Comment by Yaron10** [comment] 2017-02-22 23:06
Hello Pavel and @davidtuning,

Pavel,
👍

@davidtuning,
Thanks for reporting the issue to Pavel.
And please make sure you use Customize Toolbar v4.1.

BR
