### ISSUE TITLE
A blank line is inserted in the beginning of files

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#138] opened 2017-10-20 21:04 UTC
Hello Pavel,

Just a [link](https://github.com/pnedev/compare-plugin/issues/125#issuecomment-338052267). :)
Thank you very much.

BR

**Comment by pnedev** [comment] 2017-10-23 08:09
Thanks Yaron :+1: 

BR

**Comment by VishmayShah** [comment] 2018-02-06 06:04
I'm facing the same issue.

**Comment by VishmayShah** [comment] 2018-02-06 06:33
my issue was solved with this version
https://github.com/jsleroy/compare-plugin
they seems to be same but they are not.

**Comment by Yaron10** [comment] 2018-02-06 23:18
Hello @VishmayShah,

The problem only exists in Compare Plugin v3 which is a development version.
You can download the last stable version (v2 by Pavel Nedev) [here](https://github.com/pnedev/compare-plugin/releases).

Best regards.

**Comment by Yaron10** [comment] 2018-05-18 12:49
Hello Pavel,

Allow me to rate the basic issues as I see it.

The inserted line is still visible after Clear Compare: *major*.
The user edits a compared file and saves it. - The inserted line is saved too: **critical**.

**

Another issue.
STR:
Compare [these files](https://github.com/pnedev/compare-plugin/files/2016643/cp_test_data.zip).
Delete the inserted line.
Switch to the other file.
Delete the inserted line.
Press Next.

Result:
Access Violation.


I remembered that in some cases another empty line was inserted after re-Compare but I can't reproduce it now and I'm *not* positive about it.

**

You have probably thought about the following ideas. Just in case.

I assume it's not possible to programmatically delete the inserted lines immediately after Compare and retain proper functionality.

Would it be possible to monitor the buffer's and the inserted lines' state and respond accordingly on Clear/Close?

Thank you very much.
BR

**Comment by Yaron10** [comment] 2018-05-19 20:13
Hello Pavel,

I hope you're having a good time. :)

How about this relatively simpler solution?

Instead of inserting an empty line, insert a line congaing the following text: `Compare Plugin: please DO NOT delete or edit this line. It will be automatically removed when you Clear the active Compare or close the compared file(s).`.
Make sure the insertion is not added to the Undo list.
Highlight the lines in dark red (or purple) and blink them.

On using the navigation commands or re-Compare, check if it's still necessary to have those lines and if it is and they're not there - reinsert them first.

On Clear/Close, delete the first line without checking anything. I think this is legit as the user has been notified and warned.
On Clear or closing one file, make sure the deletion is not added to the Undo list.

It may require some fine-tuning; I'd like to get your general impression first.

Thank you.
BR

**Comment by pnedev** [comment] 2018-05-28 15:11
Hello Yaron,

A few quick remarks:

> It may require some fine-tuning; I'd like to get your general impression first.

Looks like a viable solution (with several modifications).

> On Clear or closing one file, make sure the deletion is not added to the Undo list.

Unfortunately this is not possible. I cannot exclude single entries from the Undo list. That's why CP v2 looses Undo history.
So the line will be added/removed when absolutely necessary but it will be in the Undo list. That's the best we can do. Hopefully some day we'll be able to place annotation before line 0 and this work-around will become obsolete.

Thank you.

BR

**Comment by pnedev** [comment] 2018-06-21 13:29
Hello Yaron,

Could you please try **[this](https://ci.appveyor.com/api/buildjobs/rtn3r232hwmuvmsk/artifacts/ComparePlugin.dll)** binary?
There are few things that need improvements but try it whenever is convenient to you and tell me if you notice any flaws.
Thank you very much, appreciated as always.

BR

**Comment by Yaron10** [comment] 2018-06-21 20:09
Hello Pavel,

Thank you for your work and improvements. I do appreciate it.

**

![default](https://user-images.githubusercontent.com/10229320/41739169-eb5c21c2-759c-11e8-9a6d-819bf037fcce.png)

Not inserting blanks in this case is a major improvement. :+1: 

**

![default](https://user-images.githubusercontent.com/10229320/41739332-6d7d3e66-759d-11e8-98e2-d798e2275d6b.png)

Is it necessary to insert blanks in *both files* (i.e. wouldn't inserting a blank in "prefs Backup.js" be enough)?  

**

You prevent the user from deleting the inserted line, correct?
But pressing Undo removes that line and results in a wrong behavior on navigation (e.g. press Next several times in "prefs Backup.js").

I think you can't ask the user not to use Undo. Do you agree?
So apparently on using the navigation commands you'd have to check if it's still necessary to have those lines and if it is and they're not there - reinsert them first (and vice versa: if they are not needed any more - remove them).  
What do you think? 
Would it be better to empty the Undo list?

**

If you press Undo after Clear, the line is reinserted. I understand there's nothing you can do about that.

**

Two minor issues:
1) When pressing First in "prefs Backup.js", the caret should be at the end of the inserted line if Wrap is on.
And shouldn't the actual blank blink?

2) As you can see in the screenshots above, `delete` and `this` are marked as keywords. :)
`do`, `not` `or` and possibly more can be marked as keywords in other languages.
How about using NPP `Add Comment`? - It might be a good idea regardless of the keywords.
***
This issue may seem minor at first; but it can be very common in real-life Compare and I think it's highly important. :)

Thanks again for your great work.
BR

**Comment by Yaron10** [comment] 2018-06-22 19:59
Hello again Pavel,

> SCI_STYLESETCHANGEABLE(int style, bool changeable)
This is an experimental and incompletely implemented style attribute. The default setting is changeable set true but when set false it makes text read-only. The user can not move the caret within not-changeable text and not-changeable text may not be deleted by the user. The application may delete not-changeable text by calling SCI_DELETERANGE.
>
> https://www.scintilla.org/ScintillaDoc.html#SCI_STYLESETCHANGEABLE
 
Would pressing Undo remove the inserted line if `SCI_STYLESETCHANGEABLE (false)` was set?
Regardless, setting this style should prevent the user from editing the inserted line. 

Thank you.
Have a nice weekend.

**Comment by pnedev** [comment] 2018-06-25 07:51
Hello Yaron,

Sorry for my late reply and thank you for your feedback.

> Is it necessary to insert blanks in both files

Strictly speaking it's not but I prefer it that way. It is much easier to handle and is more symmetrical (less confusing resp.).

> You prevent the user from deleting the inserted line, correct?

Sort of, yes.

> But pressing Undo removes that line and results in a wrong behavior on navigation

I'll investigate that, thank you very much. :+1: 

> I think you can't ask the user not to use Undo. Do you agree?

Sure.

> Would it be better to empty the Undo list?

I prefer not - keeping the undo is one of the major improvements in the new version. I'll try to find another way.

> If you press Undo after Clear, the line is reinserted. I understand there's nothing you can do about that.

Yes, unfortunately that's the case.

> When pressing First in "prefs Backup.js", the caret should be at the end of the inserted line if Wrap is on.
And shouldn't the actual blank blink?

I'll look into this, thanks.

> How about using NPP Add Comment? - It might be a good idea regardless of the keywords.

I actually think that it will be much better to remove the blank line text totally keeping just a new line. It will barely be noticeable and even if it reappears in some case (undo or whatever) it will not be that intrusive (most if not all text file types are actually not affected by added empty lines).
What do you think?

Otherwise, I'll simply put the text in quotes - that should do.

> Would pressing Undo remove the inserted line if SCI_STYLESETCHANGEABLE (false) was set?

Unfortunately no. I implemented this flag in the latest patch but it is not easy to handle and it doesn't work very well. The code is still there (for the future if anything changes) but it is commented at the moment. It prevents deleting the line text but doesn't prevent insertion and the undo. It is difficult to maintain because it is a style that is handled by the file's lexer and I need to constantly reapply it. The potential gain is not worth the effort.

Thanks again for your time to test and comment, I appreciate that.

BR

**Comment by Yaron10** [comment] 2018-06-25 13:53
Hello Pavel,

> Sorry for my late reply

No problem at all. Thank you for replying whenever you can.

> Is it necessary to insert blanks in both files
...
Strictly speaking it's not but I prefer it that way. It is much easier to handle and is more symmetrical (less confusing resp.).

I just want to make sure I was clear.

![default](https://user-images.githubusercontent.com/10229320/41850834-b274b0be-788e-11e8-9ae0-e5dc45dcdc59.png)

If the current implementation is easier to handle, having the inserted line only in one file is not a major gain.

> How about using NPP Add Comment? - It might be a good idea regardless of the keywords.
...
I actually think that it will be much better to remove the blank line text totally keeping just a new line. It will barely be noticeable and even if it reappears in some case (undo or whatever) it will not be that intrusive (most if not all text file types are actually not affected by added empty lines).
What do you think?
>
> Otherwise, I'll simply put the text in quotes - that should do.

If the user can edit the inserted *empty* line, they would (rightly) expect the changes to be saved.
Wouldn't that further complicate the implementation?

Also, the user might wonder why their first lines have moved to line 2; I think that an explanation in the user-guide would do.

If you decide to keep the text, quotes is a better idea. :+1:  

>   Would pressing Undo remove the inserted line if SCI_STYLESETCHANGEABLE (false) was set?
...
Unfortunately yes.

What a shame! :)
***
Is it possible to monitor Undo?
If the user presses Undo and the inserted line is removed, send another Undo (to undo the user's last action) and then reinsert the line. 

Can you check before inserting the lines and on Clear/Close if the Undo list is empty and empty it after inserting the lines and on Clear/Close? - This would reduce the "problem cases".

On Save, you can save the file(s) with the inserted line and remove it on Clear/Close. Is that correct?
Or this isn't a good approach in case the computer shuts down between Save and Clear/Close?
***

Thank you very much for the detailed reply and for your great work. Highly appreciated.
BR

**Comment by pnedev** [comment] 2018-06-25 14:44
Hello Yaron,

Thanks for the quick reply.

I didn't quite get that:

> If the current implementation is easier to handle, having the inserted line only in one file is not a major gain.

The picture you linked doesn't ring a bell either, sorry :/
How did you get to that comparison?

> Wouldn't that further complicate the implementation?

It can be done relatively easy (at least that's what I think now :) )

> Also, the user might wonder why their first lines have moved to line 2; I think that an explanation in the user-guide would do.

You are right. There is nothing else we can do anyway.

> Is it possible to monitor Undo?

I'm already doing that but it is complicated because of the different insertion/deletion scenarios. Besides, I'm also trying to let the user undo "beyond" the blank line insertion if he/she wishes to. It is possible at the moment but requires some "know-how" of compare blank handling mechanics.

> Can you check before inserting the lines and on Clear/Close if the Undo list is empty and empty it after inserting the lines and on Clear/Close? - This would reduce the "problem cases".

I'll check that, thanks for the suggestion.

> On Save, you can save the file(s) with the inserted line...

I prefer not to do it. Saving the file is currently working pretty well (at least in my tests). Have you noticed any problems with it?

Thank you.

BR

**Comment by Yaron10** [comment] 2018-06-25 19:29
Hello Pavel,

> The picture you linked doesn't ring a bell either

I simply manually added the `Compare Plugin:` line to "prefs Backup.js" and then compared. :)
And this was my suggestion: check the first lines in both files, insert the line to *one file only* and then compare.

I then added that if you had understood my suggestion correctly and responded "It is much easier to handle" - it's indeed not worth the complication.

**

> It can be done relatively easy (at least that's what I think now  :) )

:+1: 
I'm not sure though what your conclusion is. Do you think it's better to remove the text?
IMO there are pros/cons either way.

**

> I'm already doing that but it is complicated because of the different insertion/deletion scenarios. Besides, I'm also trying to let the user undo "beyond" the blank line insertion if he/she wishes to. It is possible at the moment but requires some "know-how" of compare blank handling mechanics.

That would be great. Best of luck.
It should be better than checking if the inserted line is there on each navigation, correct?

**

> Can you check before inserting the lines and on Clear/Close if the Undo list is empty and empty it after inserting the lines and on Clear/Close? - This would reduce the "problem cases".
...
I'll check that, thanks for the suggestion.

Great. Thank you.

**

> On Save, you can save the file(s) with the inserted line...
...
I prefer not to do it. Saving the file is currently working pretty well (at least in my tests). Have you noticed any problems with it?

I have not noticed any problems with Save.
I just wondered if Save required a special handling due to the inserted lines.
Obviously I trust your understanding and judgment. :)

Thanks again. I appreciate it.
BR

**Comment by pnedev** [comment] 2018-06-26 07:21
Hello Yaron,

> And this was my suggestion: check the first lines in both files...

Got it, thanks for clarifying. I prefer the current approach though.

> Do you think it's better to remove the text?

I'm about to remove the text. Any last words? ;)

> It should be better than checking if the inserted line is there on each navigation, correct?

Yes, definitely.

Thank you once again I'll write again when I make some progress.

BR

**Comment by Yaron10** [comment] 2018-06-26 13:09
Hello Pavel,

> I prefer the current approach though.

:+1: 

> I'm about to remove the text. Any last words? ;)

I'll take a rain-check on it. :)
***
Could you please try the following case while refactoring?

Manually add an empty line at the beginning of "prefs.js".
Compare.

Result:

![default](https://user-images.githubusercontent.com/10229320/41914136-c93a7a6e-795a-11e8-8651-9d1be6391751.png)
***
Thank you very much and best of luck.

**Comment by pnedev** [comment] 2018-07-02 14:57
Hello Yaron,

The last issue is a good catch :+1: , thank you. It was a subtle problem in the boundary shift algorithm.

Please try **[this](https://ci.appveyor.com/api/buildjobs/ho4620oj6m843wr4/artifacts/ComparePlugin.dll)** x86 CP binary when you have time. It fixes the problem and also optimizes further the blank line handling. For example now the insertion/deletion of the blank line is removed from the undo list if the list was empty prior the operation (as you cleverly suggested).

Please note however that the blank is still removed on undo (if the undo list was not empty before compare). There is not much we can do about that.
As to the navigation leading to wrong positioning after such case it can't be fixed. This is because the navigation strongly depends on alignment which in the other hand is connected to the compare results. If for example you manually delete (or insert) some diff lines from one of the files after compare and then again try the navigation commands you will again have weird behavior. That's because the compare results are not valid anymore and the alignment also is not OK. You'll have to re-compare to update the results. There's nothing I can do about it.

BR

**Comment by Yaron10** [comment] 2018-07-03 14:29
Hello Pavel,

Thank you very much for the last improvements. I do appreciate your work.

> If for example you manually delete (or insert) some diff lines from one of the files after compare and then again try the navigation commands you will again have weird behavior.

That's very important. :+1: 
And indeed - If you Undo and as a result some lines are added/deleted, the Compare may become invalid (dynamic Compare is not yet supported ( :) ) and this is the expected behavior).
Undoing the CP inserted line is slightly different but can still be considered the expected behavior.

How about adding a new setting `Re-Compare invalid Compare`? Possible? Complex?
If you think it's a good idea, would you mind trying the RC file from https://github.com/pnedev/compare-plugin/issues/169 and (if you like it) use it as a base?
***
> For example now the insertion/deletion of the blank line is removed from the undo list if the list was empty prior the operation (as you cleverly suggested).

:+1: 

Is the Redo list emptied when you empty the Undo list?
If it is, my suggestion may not be so clever. :)

STR:
Edit "prefs.js".
Undo.
Compare.

Result:
The Redo list is emptied.

If it *is* possible to empty one list only...
Preventing the user from editing the inserted line is a good idea.
Could you empty the The Redo list if it was empty before the user started editing the inserted line?

Great work. Thanks again.
BR

**Comment by pnedev** [comment] 2018-07-06 15:11
Hello Yaron,

I'll comment as soon as I can, sorry.

BR

**Comment by Yaron10** [comment] 2018-07-06 15:58
Hello Pavel,

No problem at all.

Allow me another comment.

> How about adding a new setting `Re-Compare invalid Compare`?

Suggesting is easier than implementing. :)
So perhaps in a future version?
Anyway, I think it would require implementing the following suggestion (otherwise, undoing the inserted line would loop and the user would not be able to undo their last action).

> If the user presses Undo and the inserted line is removed, send another Undo (to undo the user's last action) and then reinsert the line.

Thank you very much. 
BR

**Comment by pnedev** [comment] 2018-09-12 15:12
Hello Yaron,

Regarding the redo buffer - Scintilla has one Undo/Redo buffer, there are no separate buffers for both operations. So it is not possible to separately manage the Redo history.
I'll comment more later.

Thank you.
BR

**Comment by pnedev** [comment] 2018-09-17 14:47
Hello Yaron,

I have implemented basic re-compare on change functionality (_Re-Compare invalid Compare_ as you call it). Here is the x86 binary: https://ci.appveyor.com/api/buildjobs/5o0g2gpl256tv07e/artifacts/ComparePlugin.dll .

Please note that it currently doesn't have associated config setting. It will in the future.
Note also that if the files are big it might take noticeable time to refresh results (as it is full compare operation, it is just triggered automatically after certain delay). It will be user's responsibility to turn the feature off if he/she operates on big files and re-compare on change is undesirable.
The final note concerns the first alignment blank. The automatic re-compare might mess a bit the undo/redo history as blank will be removed and then probably added again.

Thank you.

BR

**Comment by Yaron10** [comment] 2018-09-17 23:27
Hello Pavel,

> I have implemented basic re-compare on change functionality...

Brilliant. :+1:
I actually had something more modest in mind but you've implemented dynamic re-compare. 
This is a major improvement and it would indeed be very convenient in small/medium files.

> Please note that it currently doesn't have associated config setting. It will in the future.

Do you think the preference should be in Settings or in the menu (for a faster toggle)?

Keeping the caret in the current position regardless of `Go to first diff...` is good. :+1: 
Should `Re-Compare active on Save` be disabled if `Re-Compare on change` is ON?
***
Are you planning more changes to the first alignment blank implementation?
If not, I'd re-read this thread and test it again. :)
(Actually it might be better to re-test it with `Re-Compare on change` OFF).

Thank you for your great work. Much appreciated.
BR

**Comment by pnedev** [comment] 2018-09-18 08:46
Hello Yaron,

> Do you think the preference should be in Settings or in the menu (for a faster toggle)?

I think it's better to place it in the menu for faster switch-off if big files are compared.

> Should Re-Compare active on Save be disabled if Re-Compare on change is ON?

I'm actually thinking of removing `Re-Compare active on Save` altogether.
`Re-Compare on change` will cover its function and if the user decides to manually handle re-comparing then he/she will do so in case of save as well.

> Are you planning more changes to the first alignment blank implementation?

There is one case that is currently not OK.
It is not connected to loosing the redo - that doesn't bother me much because if the user undoes and then makes a change redo is lost anyway (and compare with first alignment blank behaves the same way).
The problem is that sometimes a non-alignment blank appears when undoing after re-compare.
So, I'll try to figure a way to circumvent that. I'll write again when ready.

> If not, I'd re-read this thread and test it again

Many thanks for that, highly appreciated.
And yes, it is better to have `Re-Compare on change` OFF when testing initially. Later we should try it with re-compare ON.

Thank you, I'll write soon.

BR

**Comment by Yaron10** [comment] 2018-09-18 20:47
Hello Pavel,

> I think it's better to place it in the menu for faster switch-off if big files are compared.
...
I'm actually thinking of removing Re-Compare active on Save altogether.
Re-Compare on change will cover its function and if the user decides to manually handle re-comparing then he/she will do so in case of save as well.

:+1: 
Very good.

> The problem is that sometimes a non-alignment blank appears when undoing after re-compare.

I understand it's not consistent; any STR?

> I'll try to figure a way to circumvent that. I'll write again when ready.
...
And yes, it is better to have...

Great. So we'll re-test it then.
(I think the focus should also be on removing the blank line after Clear).

Thank you for your time and work. I appreciate it.
BR

**Comment by Yaron10** [comment] 2019-03-25 20:44
Hello Pavel,

An interesting NPP Undo/Redo bug in Double-View mode. 
(Just good to know. I'm not requesting a fix in CP :) ).

**STR:**
Open two files.
Move one file to the other view.
Edit the file.
Select the other file *by clicking on its tab*.

**Result:**
The Undo command is wrongly enabled until the window is refreshed.

Thank you.
BR

**Comment by pnedev** [comment] 2020-01-10 08:44
Hello Yaron,

Its been a long time and I can't really remember when last we talked (apart from you writing for the new year, it was very kind of you :) ).

I keep on working on ComparePlus when I have free time and I continue adding new features and doing improvements. But I get more busy and releasing the new compare already took years.
Thus, I'd like to release first version soon nearly as it is to its current state and leave other improvements and fixes for future versions. I still have to polish one or two things but that shouldn't take long.

About the current issue (blank line insertion) I decided that it's best if I skip line zero alignment altogether. The blank line insertion complicates things a lot and requires special handling in a lot of places. It also doesn't work well with dynamic re-compares and I cannot work around that.

So currently, when first line is not aligned I display annotation text to the user informing him/her that the lines above are not properly aligned and suggesting manual addition of blank lines in both files. That way at least there will be no hidden changes to the files messing up undo/redo and the user will be aware of that.
I also hope that in the future Scintilla is going to support annotation before the first line (and it is promising that recently Notepad++ had it's Scintilla updated). When that happens we'll have line zero alignment ready with a minimal change.

When I'm ready I'll give you a binary to see how things look if you like.

Thanks and All the best,
Pavel

**Comment by Yaron10** [comment] 2020-01-10 20:13
Hello Pavel,

Wishing you well was a duty and a pleasure. :)

Your continuous work is much appreciated.
I understand your decision to release a new version soon, and I'll be glad to try the new binary when it's ready.

Are you planning to tackle https://github.com/pnedev/compare-plugin/issues/141 now or in the future?
I don't remember the various cases but I do occasionally encounter some glitches where diffs are skipped.

Could you please update me as to the recent improvements?
https://github.com/pnedev/compare-plugin/commit/bacf7e11fc6ccb8261326dabb7a0e9037a2a86ea: Clicking on the margin selects the diff-block (which is nice and useful). Is there more to it?

Thank you and have a nice weekend.

**Comment by pnedev** [comment] 2020-01-13 09:28
Hello Yaron,

Thanks and sorry for the delay in my response.

About https://github.com/pnedev/compare-plugin/issues/141 I haven't decided yet.
I thought about leaving it for the future (maybe because I almost never trigger that problem and I kind-of automatically presume that should be the same for other users too which is wrong of course).
I will try to find some viable solution before the release.

> Could you please update me as to the recent improvements?

Honestly, I can't remember what changes I have made since we last spoke.
I did some algorithm fixes like diff blocks merging and more accurate change detection.

The first is good in some cases where there were two adjacent diffs of the same kind (let's say additions) and in-between them there was a match that was exactly the same as the ending of the second diff. In that case I move the match to the end merging the diffs together.
It schematically looks as this (diffs are in bold, matches in italic):
**ab** _c_ **dec**
is the same as
**abcde** _c_

The second is another approach in finding the changed lines between two added-removed diff blocks. Unfortunately each approach has some pros and cons - there is no universal solution to this. The new one is in general more accurate but there are cases where it might consume a lot of time. The same is also true for the old approach as well though.
I have also made it multi-threaded (using more of the available processor threads) to speed-up the change detection and the progress indication is much more smooth now (and the cancel is more responsive in that regard).

I have also made re-compares more visually appealing - the diffs coloring is preserved for as much time as possible during re-compares .

> Is there more to it?

Actually yes but have in mind that it is not completely ready yet.
If you hold `Ctrl` key while clicking the margin the diff portion will be made equal to the corresponding portion in the other file. It is basically easy diff equalization - in analog with the same functionality in BeyondCompare for example.
This is not always possible and sometimes the user might think that not the correct substitution block is taken from the other file (mainly in cases where empty lines are skipped and are not marked for that matter) but it is good enough IMO. And also if you just click the margin the substitution block from the other view will be selected for a short period giving you a clue what will be inserted as replacement.
To complicate thing even further, if you hold `Shift` while clicking the margin and the diff block is a mix of changed lines and added/removed lines the functionality will be applicable only to the same diff portion. You need to try that to get the idea it will be hard for me to explain it.
In short - if you click in the added portion margin only the added portion will be selected (and if you simultaneously hold `Shift` + `Ctrl` only the added portion will be replaced with the corresponding block from the other view - you'll equalize only the added portion). If you click in the changed line margin only that changed line will be selected and (in case you hold `Ctrl`) equalized.
I have to additionally remove the other file marking when the blocks are equalized this way.

The status bar where ComparePlus reports statistics will be updated to notify user that the files are changed and the compare might be inaccurate. If you manually change one of the files (not by clicking in the margin) this will also be indicated in the status bar. To see that you'll need to switch off automatic re-comparing on change.

I will right when I make further progress.

BR,
Pavel

**Comment by Yaron10** [comment] 2020-01-13 20:10
Continued in https://github.com/pnedev/compare-plugin/issues/220.

**Comment by pnedev** [comment] 2020-01-14 08:20
Closing this now, blank line is no longer inserted.

**Closed by pnedev** 2020-01-14 08:20 UTC
Labels: enhancement

**Comment by Yaron10** [comment] 2020-01-14 21:20
:+1:
