### ISSUE TITLE
[Enhancement] Flash current first-diff line on pressing "First"

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#143] opened 2017-10-24 22:28 UTC
Hello Pavel,

A minor improvement:
When the caret is on the first/last diff and you press First/Last, you don't get any reaction.
How about flashing that line in this case?

If Wrap-around is disabled and the Next/Prev commands are enabled (current behavior), flashing might be relevant in this case as well.

Thank you.
BR

**Comment by pnedev** [comment] 2017-10-25 08:14
Hello Yaron,

Good point, thanks.

BR

**Comment by Yaron10** [comment] 2017-10-25 17:54
Hello Pavel,

> What exactly do you mean by flashing that line?

The following Python code flashes a selection. That is: hide the selection background color for some milliseconds and then show it (repeated 3 times).
I suppose the same can be done with the diffs highlights.

```
def flashSel():
	import time
	for flashSel in range(0, 3):
		time.sleep(0.2)
		editor.hideSelection(True)
		time.sleep(0.2)
		editor.hideSelection(False)
```
Thank you for considering it.
Again - some time in the future. :)

BR

**Comment by pnedev** [comment] 2017-10-26 08:02
Hello Yaron,

I see, thanks for explaining.

BR

**Comment by pnedev** [comment] 2017-10-27 14:33
Hello Yaron,

> Again - some time in the future. :)

It seems the future has come ;)

Try this binary:
- x86: https://ci.appveyor.com/api/buildjobs/glf45cdxwcwewrcr/artifacts/ComparePlugin.dll
- x64: https://ci.appveyor.com/api/buildjobs/osx5jhu3efdja6sl/artifacts/ComparePlugin.dll

Thanks for the suggestion.

BR

**Comment by Yaron10** [comment] 2017-10-27 17:14
Hello Pavel,

The future looks good! :)

The implementation is indeed very nice. 👍 
Thank you very much. I do appreciate it.

Allow me some comments.

1) Wrap around diffs does not work.
2) I think there's no need to flash when you Compare or re-Compare. 
3) When you switch to the other file, the previously active one flashes.
4) The line before/after the first/last diff blinks. Is that intended?
If the last line does not match - that (last) line blinks if you press Last; if you press Next, the previous line blinks.
5) Related to the previous comment: is blinking the default blank line color easier to implement than blinking  the current diff color?
6) IMO repeating the flash one more time would be better. Even two more times if you keep the current flash color.

BR

**Comment by pnedev** [comment] 2017-10-28 01:58
Hello Yaron,

Thanks for the feedback.

> Wrap around diffs does not work.

Strange it works on my side. Could you give me the steps to reproduce this?

> I think there's no need to flash when you Compare or re-Compare.

I agree, it is a side effect of the implementation.

> When you switch to the other file, the previously active one flashes.

Again I do not observe this. Could you provide more details / STR?

> The line before/after the first/last diff blinks. Is that intended?

Yes, it is. I'm trying to blink one line up / down because it is more visible that way.
If the last (or the first) line is a diff then I blink that line ...

Sorry Yaron, I'm tired and need some sleep. I'll continue commenting (and answering your other posts) when I get some rest and have more free time. Thank you for the feedback, I appreciate it.

BR

**Comment by Yaron10** [comment] 2017-10-28 15:16
Hello Pavel,

I hope you slept well and have a refreshing weekend.

Could you please compare [these files](https://github.com/pnedev/compare-plugin/files/1424355/TEST.zip) when you have time?

STR 1:
Reset CP settings.
Open prefs Backup.js.
Open prefs.js.
Compare (prefs.js is active).
Press First.

Result:
The line in prefs Backup.js blinks.

**

STR 2:
Check "Wrap around diffs".
Compare the same files.
Press Last.
Press Next.

Result:
No wrap around.
(I've just noticed that if you press First and then Previous - it does wrap around).
***
Some month ago I've changed my color settings to:
```
Added=13041606
Removed=13027071
```
I think the brightness level is closer to the two other diffs colors.
I know you don't really care about that but could you please try it? 

Thanks again for your hard work and investment. Highly appreciated.
BR

**Comment by pnedev** [comment] 2017-10-30 16:30
Hello Yaron,

I see the problems, yes. They are almost fixed. Thanks for the colors suggestion too.
I'll write when the changes are completely ready.

BR

**Comment by pnedev** [comment] 2017-10-30 16:42
Hello Yaron,

You can actually preview the changes with these binaries:
- x86: https://ci.appveyor.com/api/buildjobs/38hej7r0ii3qdpv3/artifacts/ComparePlugin.dll
- x64: https://ci.appveyor.com/api/buildjobs/1t5iy26i8vjwvtm0/artifacts/ComparePlugin.dll

BR

**Comment by Yaron10** [comment] 2017-10-30 20:51
Hello Pavel,

Simply beautiful! 👍 
Blinking the diff line+icon is great.

I understand this is still WIP (wrap around).

If the first/last diff is a real line (file A) vs. a blank line (file B), you flash the real line even if file B is active.
Would it be possible to flash the blank block?

Should the [caret position setting](https://github.com/pnedev/compare-plugin/issues/140#issuecomment-340502614) (Move caret is ON) affect the flash implementation?
(The caret is at line 1 and the first visible diff at line 2; flash or not?).

Thank you very much.
BR

**Comment by Yaron10** [comment] 2017-10-31 14:10
Hello Pavel,

> If you mean that the wrap is still a problem I cannot reproduce it.

Does it work in the following case?

Compare the pref files.
Press Last.
Press Next.

Result:
No wrap around.

Also - if `prefs.js` (focal) is active, *its* last line blinks whether you press Last or Next.
If `prefs Backup.js` is active, Last blinks its last line but Next blinks the last line in `prefs.js`.

> But going to the first diff after re-compare sometimes does not work. 

👍

> Would it be possible to flash the blank block?
...
It might be possible but honestly it would be difficult to do it. Let's leave it that way for now.

Sure.
So the line in *the other file* blinks in this case and also if the last diff in the active file has been deleted after Compare.

> The caret is at line 1 and the first visible diff at line 2; flash or not?
...
It would be easier to separate those - not flash. Do you think it's better the other way?

I thought it would be easier to flash (spare the extra conditions). :)
But certainly "not flash" is much better. 👍 
(If the caret is within the first diff-line, you do flash it. Correct?).
***
Though not strictly related, I'll post here two more minor issues/questions.

**STR 1:**
Compare the same files (`prefs.js` is focal and active).
Press Last.

Result:
The vertical scroll bar seems to be in the wrong position.

![default](https://user-images.githubusercontent.com/10229320/32227352-d1c73e5a-be53-11e7-8de4-7548aa9ea7a4.png)

**STR 2:**
Compare the same files (`prefs.js` is focal and active).
Press Last.
Activate `prefs Backup.js`.
Mouse-scroll down.

Result:
The diffs are not aligned properly.

![default](https://user-images.githubusercontent.com/10229320/32227997-955c7f6e-be55-11e7-9144-9b8ac99d6dd0.png)

Thank you very much.
BR

**Comment by pnedev** [comment] 2017-10-31 14:19
Hello Yaron,

The only way to blink the blank block is to blink all blanks.
Please try this binary (as far as I remember you were using the x86 version so I'll skip the x64 link) and tell me if all of your reported issues / suggestions are fixed:

 - x86: https://ci.appveyor.com/api/buildjobs/tluqwwpqgu49b12q/artifacts/ComparePlugin.dll

Please try also the blank blink and tell me if that looks better to you than blinking the other (inactive) view corresponding diff line.
Thank you very much.

BR

**Comment by pnedev** [comment] 2017-10-31 14:23
It seems we "crossed-posts" :)
I'll check your comments some time soon, thanks.

BR

**Comment by Yaron10** [comment] 2017-10-31 14:47
Hello Pavel,

I'd like to try it more thoroughly. I'll do that later this evening.

In the meantime - I feel I must compliment you again for the new alignment.
It's so great that I've switched from Top/Bottom to Left/Right. :) 👍 

Thanks again for your hard work.
BR

**Comment by pnedev** [comment] 2017-10-31 15:53
Hello Yaron,

> I'd like to try it more thoroughly. I'll do that later this evening.

OK, thanks for testing.

Regarding your last post with detailed STRs (I mean this one: https://github.com/pnedev/compare-plugin/issues/143#issuecomment-340773771) - I know what's wrong.

Please go to Notepad++ Settings -> Preferences -> Editing and check the _Enable scrolling beyond last line_ option (it is in the right bottom corner, the second option from bottom to top).
The issues should not manifest anymore.

I have some doubts about that particular problem.
To make your cases work regardless of the above-mentioned N++ option I can always align the last documents lines (this was the initial implementation as a matter of fact). But if you compare files with a big difference in lines count (for example check 
[these files](https://github.com/pnedev/compare-plugin/files/1431307/cp_test_data.zip)
) that would lead to a big blank block at the end of the shorter file and my tests showed this affects speed and responsiveness a lot. So I removed the last lines alignment to improve performance for that kind of comparisons but it will require the user to set the mentioned N++ option. Unfortunately I cannot change the N++ settings from within CP nor can I easily check it.

What do you think would be better:
1) always align the last line making the N++ option state irrelevant but introducing performance penalty for the described type of comparisons or
2) don't unnecessarily align last lines but inform the user (point in the user guide) that the N++ option must be set to avoid the CP inconsistent behavior you faced?

Thank you for the opinion.

BR

**Comment by Yaron10** [comment] 2017-10-31 20:45
Hello Pavel,

I'd like to make sure I understand you correctly.
The options are (1) the last binary with `Enable scrolling beyond last line` OFF and (2) the previous binary with that setting ON. Is that right?

It may require some more thinking and testing.
My thoughts at this stage:

1. Some users may prefer not to use `Enable scrolling beyond last line` (personally I don't like it but it's probably a matter of getting used to).
2. Option (2): if you scroll down the shorter file and get to its end, you need to move the cursor to the larger file for scrolling further down; IMO this is a more serious downside.

If it was only the comparison time, I'd certainly vote for option (1). 
But you've also mentioned responsiveness...
***
Regarding the block flash:
I tend to think that the average user (not aware of this discussion) may find the "all-blank-blocks flash" implementation somewhat puzzling and "less correct".
If you decide to keep it, the line in the other view would still have to blink if its counterpart has been deleted.

It may not be appropriate to suggest this after all your work.
How about flashing the window? - It's not as good as flashing the diff-line but still an option.
For wrap-around you could use flash+beep.
I don't know. :)

Thanks again. I appreciate your work.
BR

**Comment by pnedev** [comment] 2017-11-01 14:25
Hello Yaron,

Thank you for the feedback.

Scrolling past the end line happened to be a Scintilla feature so I made a change to dynamically enable it in compare mode and restore it afterwards.
I also implemented kind of "smart" blinking for the blank block - the line before or after the blank block will blink depending on the search direction.

You can try this binary to get the idea and inspect the behavior further:
- x86: https://ci.appveyor.com/api/buildjobs/7phteq9wya4bd33b/artifacts/ComparePlugin.dll

BR

**Comment by Yaron10** [comment] 2017-11-01 21:31
Hello Pavel,

The "smart" blinking is indeed smart. Great work. 👍

STR:
Open the pref files.
Delete line 186 in `prefs Backup.js`.
Compare (`prefs.js` is focal and active).
Switch to `prefs Backup.js`. 
Press Last.
Press Last again.

Result:
No blink.
***
> Scrolling past the end line happened to be a Scintilla feature so I made a change to dynamically enable it in compare mode and restore it afterwards.

As usual you end up with a clever solution. 👍 
There are still some issues. I don't know which are related to the scope issue and which are different and separate ones.

STR:
Compare the pref files in a not-maximized window.
Press Last.
Switch to the other file.

Result:
The diffs are not aligned properly.
(Refreshing re-align them).

**

STR:
Open the pref files.
Position the caret at the end of `prefs Backup.js`.
Compare (`prefs.js` is focal and active).
Switch to `prefs Backup.js`. 
Press Last.

Result:
No move to the last diff.

**

STR:
Compare the CSV files (the larger one is focal and active).
Press Last.
Press Last again.

Result:
Each time we move to a different position. 
Also - switching to the other file, changes the position.

**

STR:
Compare the CSV files (the larger one is focal and active).
Press Last (until you see line 10000).
Don't switch to the other file but only hover over it and scroll up. 

Result:
We jump to line to line 4900 or so. Would you consider that the expected behavior?
Also - as I've mentioned earlier, you can't scroll down to the end of the larger file when hovering over the shorter one. 

Thank you. I appreciate your work.
BR

**Comment by pnedev** [comment] 2017-11-02 18:14
Hello Yaron,

I see the issues, thanks.
I'll revise them as soon as I can.

BR

**Comment by Yaron10** [comment] 2017-11-02 20:53
Hello Pavel,

Thank you. I appreciate it.

BR

**Comment by pnedev** [comment] 2017-11-17 16:10
Hello Yaron,

All STRs are fixed except the last one - you can try the binary from https://github.com/pnedev/compare-plugin/issues/141. Here is the same link for convenience:
https://ci.appveyor.com/api/buildjobs/5wj86c8fin988amv/artifacts/ComparePlugin.dll

> Also - as I've mentioned earlier, you can't scroll down to the end of the larger file when hovering over the shorter one.

That's normal - if you'd like to see the block present at the end of only one of the files it is perfectly fine to  hover and scroll over it and not the other. I'll leave this as minor "inconvenience" - it is the lesser 'evil' compared to the performance penalty when files differ a lot in size.

Thanks for the feedback.

BR

**Comment by Yaron10** [comment] 2017-11-17 21:21
Hello Pavel,

> All STRs are fixed except the last one...

Very nice. 👍 
Thank you very much. Highly appreciated.

> That's normal - 
...

That's indeed only a minor issue.

BR

**Comment by pnedev** [comment] 2017-11-28 16:52
Hello Yaron,

The last STR is related to the second one from here
https://github.com/pnedev/compare-plugin/issues/141
so I'll close this issue.

BR

**Closed by pnedev** 2017-11-28 16:52 UTC
Labels: enhancement, question

**Comment by Yaron10** [comment] 2017-11-28 22:08
👍
