### ISSUE TITLE
[Enhancement] Properly align matches in Wrap mode

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#51] opened 2016-04-15 21:23 UTC
Hello Pavel,

[Reading](https://github.com/pnedev/compare-plugin/issues/30#issuecomment-210341657) you've modified the empty lines handling, could you please try the following?

[prefs](https://github.com/pnedev/compare-plugin/files/217614/prefs.zip).

Check View -> Wrap.
Delete line 61 in prefsBackup and compare.
[Result](http://s23.postimg.org/4l4jg630r/Align_Matches.png): lines 64 are not properly matched.
Would it be possible equalize the length of the empty line to that of its counterpart?
Would it seriously affect performance? 

(Tested with an older version as I'm currently having an [issue](https://github.com/pnedev/compare-plugin/issues/30#issuecomment-210142117) with the latest commit).

BTW, what do you think of the new Compare/Clear icons? :)
I'm not a pro and It's hard to get a better result.

Thank you.
BR

**Comment by pnedev** [comment] 2016-04-16 01:08
Hello Yaron,

Another time, I need some sleep. Thanks.

BR

**Comment by pnedev** [comment] 2016-04-16 01:22
A quick test with latest master -> I cannot reproduce any issue with the _prefs_.
I'll try again later.

BR.

**Comment by pnedev** [comment] 2016-04-17 22:22
Hello @Yaron10 ,

> Would it be possible equalize the length of the empty line to that of its counterpart?

That's strange, why would you need such thing?

This issue seems related to the VS2013 Express compiler as discussed in #30 .
Do you see this with the dll xylographe sent you?.

About the icons, as I told you those are a bit misleading and I'm not currently planning to implement those, sorry. Perhaps at some time in the future if we find suitable icons. Thanks.

BR

**Comment by Yaron10** [comment] 2016-04-18 01:36
Hello Pavel,

This issue exists in older versions and also in the DLL xylographe sent me.

Regarding the icons: I've created new ones and asked your opinion about them.
It was a BTW-question. Never mind.

Thank you.

BR

**Comment by pnedev** [comment] 2016-04-18 10:39
Hello Yaron,

I didn't see the new icons, sorry. Can you send them again?
Thanks.

BR

**Comment by pnedev** [comment] 2016-04-18 12:18
Hello Yaron,

Yes, I see what you mean. I was looking at the compare validity, not the blank lines.
You are right, the blanks are not enough, that's a bug.

Now I see your idea behind this

> Would it be possible equalize the length of the empty line to that of its counterpart?

This is something worth considering as it will ease things in several scenarios (will be good especially when you trigger Wrap Mode on/off while the compare is active - now this is not handled and changes the compare layout) but will inevitably affect badly other use cases.

I will consider this, thanks for the report and the idea.

BR

**Comment by Yaron10** [comment] 2016-04-20 18:05
Hello Pavel,

Thanks for considering it.

BR

**Comment by xylographe** [comment] 2016-04-20 19:11
I was finally able to reproduce this improper alignment issue. In [this screenshot](https://www.dropbox.com/s/5wkyctmtqh4bmgv/NPP-CP-prefs-002.png?dl=0) line 67 on the left and line 67 on the right are not aligned. I didn't delete anything, just triggered "Compare" and scrolled down.

CP 81dbed4d26bf2c86cae46cfdff6cbc4edd27702e

**Comment by pnedev** [comment] 2016-08-31 11:03
Hello Yaron,

This is fixed in latest master.
Please note that only the empty lines are wrap-synchronized.
This means that if two lines are marked as modified and one of them is considerably shorter (and the other is wrapped) then the next lines are again misaligned. Unfortunately this is very difficult to circumvent but with the latest change and the dynamic synchronization of wrapped lines I think this is not much of a problem.

Thanks again for filing this issue.

BR

**Comment by Yaron10** [comment] 2016-08-31 17:11
Hello Pavel,

I never thought of indentation as a solution to this issue. Very clever. :+1: 
Another major improvement. Many thanks.

Could you please compare [these](https://github.com/pnedev/compare-plugin/files/447877/prefs.zip) files?
The length of (the blank) line 64 in prefsFFbackup.js does not match its counterpart in the other file.
Some fine-tuning? :) 
***
> Please note...
>  I think this is not much of a problem.

Indeed. 
Thanks again for the synchronization of wrapped lines. Absolutely great.

BR

**Comment by pnedev** [comment] 2016-09-01 08:44
Hello Yaron,

The problem  comes from the wrap type. The wrap type by default is "word boundary wrap" meaning that your text will be transferred to the new line on word boundary. Now the blank line indentation is exactly the length of you text line but it is composed of spaces and thus doesn't have any words (and boundaries respectively). That means it will be wrapped on char basis so each line will be filled with spaces exactly to the place of wrapping. Let me illustrate this.

Original text line:
"_Wrap misalignment issue_"
Length is 23 chars, the blank line will also be 23 chars.

This is how those are wrapped if wrap position is at char 14:

Marks:
'0' is a space
'#' is the wrap position

Text line:

1 _Wrap0_
2 _misalignment0#_
3 _issue_

Blank line:

1 _0000000000000#_
2 _0000000000_

So the text is 3 wrapped lines while the blank is 2. This is because wrapped line 1 in the text case is 5 chars long but in the blank case it is 13 chars.

This can be circumvented of coarse. If I configure the wrap type in compare mode to be "char" aligned then you would get

1 _Wrap0misalign#_
2 _ment0issue_

but that doesn't look good.

The other solution would be to add more spaces to the blank line (more than the original text length) but that would require considerably more processing and the re-sizing adjustment would be very difficult to handle (on re-size the wrap position will change). 
Thus I think such approach is not justified and the way it is now is a good compromise.

What's your opinion?
Thanks.

BR

**Comment by xylographe** [comment] 2016-09-01 09:06
Hello Pavel,

Would line wrap be different if you were to use U+00A0 (Unicode NO-BREAK SPACE)?
For example, `"Wrap0misalignment0issue"` ⇒ `"~~~~0~~~~~~~~~~~~0~~~~~"` (where `'0'` is space, and `'~'` is no-break space).

**Comment by pnedev** [comment] 2016-09-01 09:15
Hello @xylographe ,

I'm not sure I understand you correctly.
You mean to use for blank line indentation U+00A0 ?
That wouldn't help because if the line cannot be broken on word boundary (word is too long to fit in a single wrap line) it will be broken on spot (fall-back to char wrap type) which will lead to the same result.

Finding-out exactly where are each word boundaries in order to use U+00A0 for word spaces and normal space between words is an overkill.

Thanks

**Comment by xylographe** [comment] 2016-09-01 10:23
Hello Pavel,

If I understand correctly, at the moment the blank line that represents a text line of **N** characters is a line of **N** space characters: `Wrap0misalignment0issue` ⇒ `00000000000000000000000` (both lines have 23 chars). But the *break points* (word boundaries) are different, hence these two logical lines may occupy different number of lines in Scintilla view (in your example 3 for the text line, 2 for the corresponding blank line).

Ideally, both text line and blank line should (after wrapping) occupy the same number of lines in their view. I thought (but I may be completely wrong), that a sequence of no-break spaces might be interpreted as a word, then the word boundaries in text line and blank line would be at the same position:
```
Wrap0misalignment0issue (text line)
~~~~0~~~~~~~~~~~~0~~~~~ (blank line)

(space in text line remains space in blank line, non-space characters in text line become no-break space characters in blank line)
```

In both lines the break points would be at the 0s (representing space characters), while the ~s (representing no-break space characters) in the blank line would still look like a normal space.

**Comment by pnedev** [comment] 2016-09-01 13:12
Hi @xylographe ,

Yes, your assumption seems totally right but that means I'll need to compose a blank line of the format
~~~~0~~~~~~~~~~~~0~~~~~
This means that I'll have to parse the text line and discover where the word boundaries are, locate the real spaces, etc. which is time consuming.
The idea is excellent otherwise, thanks.

BR

**Comment by Yaron10** [comment] 2016-09-01 17:40
Hello Pavel,

An excellent explanation. Thank you very much.

I certainly see the problem in the potential solutions. 

> and the way it is now is a good compromise.

Please don't consider the following question ungrateful. :)
If the lines are not properly aligned, is the extra code worthwhile?
On the one hand it does reduce the gap; OTOH it may seem even more buggy in some cases (the user might think: "The dev has addressed the issue but the solution is not perfect.").
I don't know.

*

How about copying the line from one file to the other and setting the color to transparent?
IOW: blank lines would have the same (*invisible*) content as their counterparts.
Complex? Performance?

BR

**Comment by pnedev** [comment] 2016-09-02 07:38
Hello Yaron,

I'll think about it. If I find a way to fix this without much complications I'll do it.
Thanks.

Interesting suggestion by the way but it seems a bit too much to me.

BR

**Comment by xylographe** [comment] 2016-09-02 08:57
Hello Yaron and Pavel,

> How about copying the line from one file to the other and setting the color to transparent?

This would surely be more efficient than parsing the text line to create a blank line. And it should work perfectly in top/bottom layout, and also in left/right layout iff both views have the same number of columns (character cells). Which only leaves left/right layout with views of different width.

**Comment by pnedev** [comment] 2016-09-02 09:15
Hello all,

This will introduce more problems and is thus not reasonably applicable.
Hidden text is still a text and you would like to be able to edit the file.

@xylographe ,

Your solution seems bound to UTF8 and if the compared files are true ANSI it won't work I suppose.

I'll need to dynamically change the spaces count - this is the only reasonable approach.
I'll leave it for some time in the future.

Thank you both for the suggestions.

BR

**Comment by xylographe** [comment] 2016-09-02 09:27
Hello Pavel,

> Hidden text is still a text and you would like to be able to edit the file.

Good point.

**Comment by Yaron10** [comment] 2016-09-02 17:21
Hello Pavel and xylographe,

Thank you.

> I'll leave it for some time in the future.

That's good. I appreciate it.
Wouldn't it be better to reopen this issue for the time being?

Best regards.

**Comment by pnedev** [comment] 2016-09-07 14:51
Hello Yaron,

Done.

BR

**Comment by Yaron10** [comment] 2016-09-07 18:46
Thank you Pavel. :)

**Comment by pnedev** [comment] 2016-09-08 14:26
Hello all,

Wrap should be OK now, please try and report if there are any errors.
Thanks.

BR

**Closed by pnedev** 2016-09-08 14:26 UTC
Labels: bug

**Comment by Yaron10** [comment] 2016-09-08 21:38
Hello Pavel,

Excellent! I take my hat off.
Thank you very much.

I'm sure this fix (as others) is time and thought consuming.
If you are tired of it, please ignore the following lines.

It's actually mu fault: when I opened this issue I was only focusing on blank lines.
Your latest commit fixes this issue brilliantly. 

But if we look at the broader picture (figuratively and literally) some diffs and lines above and below them may not be aligned.

1) If you focus on the line the cursor is on, the line below [may not be aligned](https://s9.postimg.org/m38b0fl2n/Cursor_Line.png) (different length). 
2) If you look at the entire window (not just at the line the cursor is on), [not all diffs are aligned](https://s17.postimg.org/ajkfhfbnz/Entire_Window.png).

I love the latest fix but I assume it has some impact on the comparison performance. 
So my question is this:
In terms of concept, why should there be a difference between blank lines and diff lines?
And point (2) enhances my wonder whether this fix is justified.

What do you think?

Again: your work is absolutely great, and I do apologize for sharing those thoughts at this stage.

Best regards.

**Comment by Yaron10** [comment] 2016-09-08 22:00
Hello again,

> This means that if two lines are marked as modified and one of them is considerably shorter (and the other is wrapped) then the next lines are again misaligned. Unfortunately this is very difficult to circumvent **but with the latest change and the dynamic synchronization of wrapped lines I think this is not much of a problem**.

Just to sharpen my point: perhaps with the dynamic synchronization of wrapped lines my original issue here is not much of a problem either.

Thank you.
BR

**Comment by pnedev** [comment] 2016-09-09 08:15
Hello Yaron,

> Just to sharpen my point: perhaps with the dynamic synchronization of wrapped lines my original issue here is not much of a problem either.

Well yes, blank lines are not much different from regular modified lines. But it is easier (at least relatively) to implement wrapped blank lines (to reflect the wrapped line in the other view) than to sync the wrap of modified lines.

> I assume it has some impact on the comparison performance.

The performance impact is negligible unless you have a lot of wrapped blank lines which will almost never be the case.

If in time the performance penalty proves to be an issue then a setting can be implemented to switch off the dynamic blanks wrapping feature.

Thanks for commenting.

BR

**Comment by Yaron10** [comment] 2016-09-09 14:38
Hello Pavel,

Thanks for the explanation. I appreciate it.

I tend to set too much importance on consistency.
Your attitude is better. :)

And thanks again for this fix. Brilliant work! :+1: 

BR

**Comment by pnedev** [comment] 2016-09-09 15:32
Consistency is a good thing in general :)

Thank you.

BR

**Comment by Yaron10** [comment] 2016-09-09 15:42
True, but life is full of compromises and one has to learn to except them.

BR
