### ISSUE TITLE
Incorrect Comparison 

### ISSUE THREAD

**Issue by adhoniran** [pnedev/compare-plugin#223] opened 2020-01-22 00:23 UTC
Hi,

This plugin is great.
I am testing it because I want to use it in my day-to-day, but I just found an incorrect comparison behavior when the line starts with a single character separated by space and the compared line have the same first character.

The software ignores the text after the first character and considers the lines like equals.

I just added some screenshots:

http://pasteall.org/pic/1e225a3e36cf3ebefb15cad3731edc7a
http://pasteall.org/pic/9e7b82fdf9236412672e77923b833342

Note: Microsoft Edge is detecting this URL as malware, but It's a false positive. Google Chrome opens the URL normally.

If you prefer not to open the URL compare two files with the contents below:

FILE 1

! ================================================================
! CONFIG 1
! ================================================================

interface vlan 69   
 tagged te 0/20,40

FILE 2

!
! 		  
! 

interface vlan 69   
 tagged te 0/20,40

**Comment by pnedev** [comment] 2020-01-22 08:43
Hi,

I couldn't reproduce the issue on my side.
Could you tell me your version of Notepad++ and your version of Compare plugin?

BR

**Comment by adhoniran** [comment] 2020-01-23 14:00
Hi,

Very strange, I tried using another PC now and comparison is fine to the text.
The Notepad++ version are the same (I think) and the Compare plugin too.

I can to confirm the versions today, later, and repeat the test.

**Comment by adhoniran** [comment] 2020-01-24 03:36
Hi, 

The Notepad++ version is 7.8.2 and the Compare plugin version is 2.
I tried again now and comparison worked fine.   :/

**Comment by pnedev** [comment] 2020-01-28 09:01
@adhoniran ,

Very strange. I have never seen such problem or heard of it before.
I'll close the issue now but if you see similar behavior again please write back.

**Closed by pnedev** 2020-01-28 09:01 UTC
Labels: question
