### ISSUE TITLE
Known Issues / Reminders (2)

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#73] opened 2016-05-24 13:45 UTC
[Caret position after Clear Compare](https://github.com/pnedev/compare-plugin/issues/66).
[Clear-compare closes original in main view](https://github.com/pnedev/compare-plugin/issues/48).
[Undo list is emptied after Compare](https://github.com/pnedev/compare-plugin/issues/57).

---

Start NPP.
Open 2 new empty files.
Compare.

Result:
The second file is closed.

---

Clear the Recently Closed Files List or have only two files there.
Open two files.
Set First.
Switch to the other file.
Set First.
Close the current file.
Set First.

Result:
The navigation commands/buttons are enabled.

**Comment by Yaron10** [comment] 2016-06-09 20:59
A NPP issue:

Comparing a UTF-8 file to a windows-1255 file - the Encoding-Mismatch warning is not displayed.

**Comment by pnedev** [comment] 2016-12-05 14:31
Hello Yaron,

The following issue

> Clear the Recently Closed Files List or have only two files there.

> Open two files.
> Set First.
> Switch to the other file.
> Set First.
> Close the current file.
> Set First.
> 
> Result:
> The navigation commands/buttons are enabled.

seems fixed. Could you try it once again at your side?
Thank you.

BR

**Comment by Yaron10** [comment] 2016-12-06 01:46
Hello Pavel,

**Clear the Recently Closed Files List or have only two files there.**

The issue still exists on my machine.

This is most definitely not a common use-case.
It may, however, indicate a more serious underlying issue. What do you think? 
If you're tired of it, please leave it.

Thank you very much.
BR

**Comment by pnedev** [comment] 2016-12-06 09:02
Hello Yaron,

I'll have to try on my Win7 machine.
I cannot reproduce this under Wine.
Thanks.

BR

**Comment by Yaron10** [comment] 2016-12-06 16:22
Hello Pavel,

Thank you. I do appreciate it.
You deserve a lot of compliments for your work and attitude.

BR

**Comment by pnedev** [comment] 2016-12-11 01:45
Hello Yaron,

Just to let you know - on my Win7 setup I'm reproducing the issue consistently.
And you are right - it might indicate some underlying problems.
I'll need to investigate more. Thanks.

BR

**Comment by Yaron10** [comment] 2016-12-11 02:02
Hello Pavel,

Thank you. I do appreciate it.

Please [take it easy](https://github.com/pnedev/compare-plugin/issues/102#issuecomment-266255439). :)

BR

**Comment by pnedev** [comment] 2016-12-11 02:36
Hello Yaron,

One clarification:
To reproduce the issue you simply need to clear the recent list, open a file and then close it.
It makes the problem even worse as it is easily observable.

BR

**Comment by Yaron10** [comment] 2016-12-11 17:57
Hello Pavel,

> To reproduce the issue you simply need to clear the recent list, open a file and then close it.

And reopen it. - On my machine.
Anyway, a good catch.

Some comments about "Restore Recently Closed File":
When this feature was first introduced it didn't work properly (e.g. the command's text was often missing).
Don has fixed it since (by "embedding" the text) but now it can't be localized.

I use the MenuIcons plugin.
If you clear the Recent Files list, open a file and close it - most of the menu's icons disappear.
Franco Stellari (MenuIcons Developer) has tried to fix it but to no avail.

I'm not sure these facts are relevant.
Yet, there might be something wrong in the implementation of this dynamically created command which is the cause of our issue.

Thank you very much.
BR

**Comment by pnedev** [comment] 2016-12-12 08:48
Hello Yaron,

Interesting. That might have something to do with the issue, you are right, thanks.

BR

**Comment by Yaron10** [comment] 2016-12-12 19:34
Hello Pavel,

Anyway, IMO this is a minor issue which can remain in the Known-Issues list.

Thank you.
BR

**Comment by Yaron10** [comment] 2017-02-21 01:38
Related: [buttons state](https://notepad-plus-plus.org/community/topic/13272/comment-line-style-for-user-defined-language/4).

Thank you.

**Comment by pnedev** [comment] 2017-02-21 08:59
Thanks Yaron.

**Comment by pnedev** [comment] 2017-02-28 13:23
Hello,

FYI:

> Related: buttons state.

It is fixed with https://github.com/pnedev/compare-plugin/commit/e11d59f956d3ffcc08fb3f830834dece83d2a5bb.

BR

**Comment by Yaron10** [comment] 2017-03-01 03:01
Hello Pavel,

It works like a charm. 👍 
Thank you very much.

BR

**Comment by pnedev** [comment] 2018-09-17 11:42
Hello again Yaron,

Regarding point 2 from my previous comment (empty files comparison) - this is fixed as noted here:
https://github.com/pnedev/compare-plugin/issues/173 .

Thanks.
BR

**Comment by Yaron10** [comment] 2018-09-17 14:32
Hello Pavel,

> This thread needs to be revised...

Indeed.

> Thanks to @SinghRajenM, this issue is fixed - #66 .
Because of the new alignment approach this issue is no longer relevant - #57 .

:+1: 

> I cannot reproduce this problem:
Clear the Recently Closed Files List or have only two files there.
...

I can not reproduce it either.
Great job. :)

> Do you think3 need to be added to the new known problems thread?

As you understand.
If you open a new thread for https://github.com/pnedev/compare-plugin/issues/48, why not adding it too?

Thank you. I do appreciate your work.
BR

**Comment by pnedev** [comment] 2018-09-17 15:03
Hello Yaron,

OK, I'll close this thread and later open a new one listing the remaining known problems.
Thank you.

BR

**Closed by pnedev** 2018-09-17 15:03 UTC
Labels: invalid, wontfix
