### ISSUE TITLE
"Git diff" EOL format

### ISSUE THREAD

**Issue by xylographe** [pnedev/compare-plugin#74] opened 2016-06-01 08:47 UTC
- git config is `core.autocrlf=true`
- text files in the git repository have LF EOL
- checked out text files have CR+LF EOL

Result after triggering "Git diff",
![cp-git](https://cloud.githubusercontent.com/assets/8535293/15703220/6af39676-27e4-11e6-9a40-032a540e0cee.png)

It would seem that `core.autocrlf=true` is ignored. But the status line displays "Dos\Windows".
Just a very minor issue, because CP ignores EOL differences.

Note that although the file has not been modified after `git checkout`, the first line in the example above is flagged as different, I think, this might be caused by the UTF-8 BOM, although the status line does show "UTF-8-BOM" (same as working copy).

**Comment by pnedev** [comment] 2016-06-01 10:59
Hello @xylographe ,

I'll check this, thanks for reporting.

BR

**Comment by pnedev** [comment] 2016-06-01 12:27
Hello @xylographe ,

That is a bit tricky.
I can convert the EOL to the new file setting but:

1) the user will get the wrong impression about the saved or repo file content
2) if you convert the EOL format the document will appear as dirty and when you "Last Save Diff" you'll get "Files match". Now if I have silently converted the temp file EOL to that of the new file you won't see any difference even if you have enabled "See all characters" in N++. But still the new file appears dirty.

I think the right approach in case of EOL discrepancy would be to report
"Files line endings differ. Check for other differences? - Yes/No" (defaulting to 'Yes')
and not change the temp EOL type at all.
This way you'll know that the files actually differ - EOLs don't match but you can ignore that and compare their contents anyway.

Tell me what you think.

BR

**Comment by xylographe** [comment] 2016-06-01 15:08
Hello Pavel,

Thank you for examining this issue.

I don't like the idea of an unnecessary, yet disruptive message box at all.
There is no *real* difference, it's just that git respects its `core.autocrlf` setting, while CP does not.

The compare itself works fine with different line endings. Also copying lines from temp file to focal file works fine, because the line endings are converted from LF to CRLF. Hence, I think, doing nothing is the best way to 'resolve' this issue. (Which can be closed, If you agree.)

**Comment by pnedev** [comment] 2016-06-01 23:37
Hello @xylographe ,

> There is no real difference

If you don't have git EOL config and your index is clear (no changes) try using N++ convert to Unix/Windows line endings on a file from the repository (save that). Then from the console try `git diff`.
It will report that the file is changed but yet if you do CP "Git Diff" you'll get that the file is unchanged.
That's weird and inaccurate.

BR

**Comment by pnedev** [comment] 2016-06-01 23:44
Other solution would be to compare EOLs if "Ignore spaces" is not set.

BR

**Comment by xylographe** [comment] 2016-06-02 11:15
Hello Pavel,

Under Windows `core.autocrlf=true` is the default setting : 
```
PS> git config -l | grep autocrlf
core.autocrlf=true
PS> git config -l --system | grep autocrlf
PS> git config -l --global | grep autocrlf
PS> git config -l --local | grep autocrlf
```
As you can see, there is no *explicit* `core.autocrlf` setting anywhere, because it's unnecessary.

This is what happens after replacing CRLF with LF in NPP : 
```
PS> git diff
warning: LF will be replaced by CRLF in secc.ps1.
The file will have its original line endings in your working directory.
PS> git add secc.ps1
warning: LF will be replaced by CRLF in secc.ps1.
The file will have its original line endings in your working directory.
PS> git status
On branch master
nothing to commit, working directory clean
```

There is nothing to commit, because inside the Git repository text files have LF line endings by default. After a new `git checkout` the text files in the working directory will have CRLF line endings again (the explicit change in NPP is undone).

> Other solution would be to compare EOLs if "Ignore spaces" is not set.

That would make "Git diff" useless, because every line in the 'Old' view would be red (minus) and every line in the 'New' view would be green (plus). To avoid that users would be forced to set `core.autocrlf=false` (the Unix/Linux default) in their global Git config, opening a can of worms.

The proper solution would be to use the same heuristics as `git checkout` when retrieving the temp file from the Git index (i.e. use `.gitattributes` and git configuration to determine if it's a binary or text file, and apply the appropriate line ending conversion in case of a text file). I have no idea if git2 lib can do that?

**Comment by xylographe** [comment] 2016-06-02 13:02
Hello Pavel,

I'm a little confused. I did a byte-to-byte compare between `secc.ps1` and `secc.ps1_Git` (the temp file) with cmp(1), and it turns out that these files are *identical*. They both start with an UTF-8 BOM and both have CRLF line endings. So, why does NPP/Scintilla display LF line endings in `secc.ps1_Git`, while the status line shows "Dos\Windows"?

**Comment by pnedev** [comment] 2016-06-02 13:54
Hello @xylographe ,

> As you can see, there is no explicit core.autocrlf setting anywhere, because it's unnecessary.

OK, but there might be. It is a config after all and the user can freely set `autocrlf` to false.

> The proper solution would be to use the same heuristics..... I have no idea if git2 lib can do that?

I think this is an overkill. Unfortunately I'm not familiar at all with libgit2. It's the first time I'm looking at it.

> Under Windows...

I am actually working under Linux and for N++ I'm using Wine.

> That would make "Git diff" useless, because every line in the 'Old' view would be red (minus) and every line in the 'New' view would be green (plus).

Well, I have seen source files in the past having mixed line endings. This is a mess and being able to catch that with compare is a good thing IMHO.
Also the above is not quite true. If you ignore comparing spaces we'll ignore EOLs also.
I can also implement "Ignore line endings" for example.
If you have cloned Git repo then your line endings would be what they are in the repo. If you explicitly change them then you'll have that discrepancy and it is normal for "Git Diff" to show it. If you don't change line ending by yourself you will not differ from the repo and the above statement is not valid.

> In fact, when I "Reload" secc.ps1_Git in NPP and trigger "Compare", I get the expected 'Files "secc.ps1" and "secc.ps1_Git" match.'

I'll investigate that, thanks.

BR

**Comment by xylographe** [comment] 2016-06-03 02:50
Hello Pavel, 

> If you explicitly change them

But that is the point. In my original post, I did **not** change anything after `git checkout`.
And the "Git diff" temp file is identical (as expected) to the file in the working directory.

If CP would compare real file to temp file without 'tricks' it would report "Files match". But as you can see in the image in my original post, this doesn't happen. CP claims the first lines are different, and also CP seems to (instruct Scintilla to) replace CRLF in the temp-file *buffer* with LF. The temp file itself has CRLF line endings, the displayed temp-file *buffer* has LF line endings.

**Comment by pnedev** [comment] 2016-06-06 11:45
Hello @xylographe ,

I think we are mixing two different issues here.

In my previous post I was referring to the EOL issue and more precisely to the case when you are running on Linux, don't have Git config forcing certain EOL type and you change on a clear index the line endings format from N++ (Convert EOL to UNIX/Windows). Save the file and then in the console if you do `git status` you'll see that the file appears to be changed. `git diff` in the console will show the EOL diffs but CP will say that the file is not changed compared to Git base. This is a discrepancy and it comes from the fact that CP ignores EOL differences.

In you post you are referring to the issue with your secc.ps1 file.
I don't know exactly what is causing this but I have an idea.
The problem might be coming from the fact that the "Git Diff" is the only command that actually pastes raw text content to the temp file. The temp file will have the encoding and EOL setting of the new file because of the fact that the new file is actually copied in the temp folder as temp file. So at first, temp and the new file are actually the same. Then the content of the temp file is discarded and the git raw text data is pasted instead. This leaves the encoding of the file as it was before the paste and this is also valid for the EOL type. This is for sure why you are seeing the file as DOS/Windows type but you actually have UNIX-like line endings (that are coming from the raw Git data).

Now, this copying of the file was a good idea in case of Last Save (because by copying the new file to temp we are actually preserving the new file type and we are directly getting the saved data). It was a good idea for SVN also because we are copying then not the new file but the SVN committed file.
So the only problem is with the Git where we don't actually have a file from the Git repo but raw content.

I'll think about what can be done in this case (the file encoding types are not something I'm familiar with).

BR

**Comment by pnedev** [comment] 2016-06-06 11:53
Perhaps we need to use `git_blob_filtered_content` instead of `git_blob_rawcontent` in our case.
I will do the changes and give it a try but I suspect we'll need a new version of the LibGit2 library. According to the LibGit2 API `git_blob_filtered_content` is available since v 0.20.0 and our current DLL is v 0.18.0.
I don't know yet how I can generate DLL on my own.

BR

**Comment by pnedev** [comment] 2016-06-06 12:48
Hello again @xylographe ,

The changes are in https://github.com/pnedev/compare-plugin/commit/d3ac2ccd50ac4846682ca7306b7241d55a66ba41 but we'll need libgit2 dll v0.20.0 or greater. Otherwise the corresponding API is not present and initializing the library is failing.

I think this is the way to go with "Git Diff" issues - migrate to newer LibGit2 version.

BR

**Comment by xylographe** [comment] 2016-06-06 16:37
Hello Pavel,

I tried libgit2-0.24.0. Unfortunately ==> "Failed to initialize LibGit2 - operation aborted"

**Comment by xylographe** [comment] 2016-06-07 07:43
Thank you, Pavel.
Using `git_blob_filtered_content` i/o `git_blob_rawcontent` (master d53fb366a86d1ef823ffb71ffe77cefc187a3881) has resolved this "EOL format" issue.

The second anomaly—first line differs in UTF-8-BOM encoded file that has not been altered since git checkout—still exists. I'll open a new issue for that later (it has near-zero priority).

**Comment by pnedev** [comment] 2016-06-07 07:45
Hello @xylographe ,

Can you try _secc.ps1_ "Git_ Diff" again with latest master?
Just replace your _git2.dll_ with the new one from _src/LibGit2_

Thanks.

BR

**Comment by pnedev** [comment] 2016-06-07 07:46
A, just saw your post.

OK, thanks,

BR

**Closed** 2016-06-07 07:47 UTC
Labels: bug

**Comment by xylographe** [comment] 2016-06-07 08:27
Hello Pavel,

That was the second time our comments 'crossed' within less than 30 seconds. :)

While I was 'playing around' with the new "Git diff" I suddenly got a "different encodings" warning. Very strange, and I have not been able to reproduce, but when I do, I will open a new GitHub issue on that too.

About "CP ignores EOL differences" – I think, detecting EOL differences should be controlled by a separate option ("Ignore EOL", perhaps). Under Windows it is not uncommon that some text processing tools (from msys, for example) produce Posix text format (LF) files, or even files with mixed line endings. Hence, it would be rather inconvenient if it would not be possible to turn off EOL difference detection in CP. Under Windows Git will normalise line endings when changes are committed, hence, the repository will remain 'clean' (presuming Git default behaviour has not been overruled).

**Comment by pnedev** [comment] 2016-06-07 08:35
Hello @xylographe ,

> ... I suddenly got a "different encodings" warning

I've seen that too. I agree that this needs further investigation.
I also agree that a separate "Ignore EOL" option is needed. I'll open enhancement issue for that.

Thanks.

BR

**Comment by pnedev** [comment] 2016-06-07 10:42
Hello @xylographe ,

About the different encodings warning.
I'm able to reproduce this this way:

1) If you are about to compare two files with the same encoding and DOS/Windows EOLs.
2) Change the EOL type of one of the files - "Convert to UNIX line endings".
3) Don't save, just reload the file (I'm using the Reload plugin for that) - it will have again DOS/Windows EOLs but N++ will report in the status bar that the file is UNIX type.
4) At this moment if you look at the "Encoding" sub-menu you'll notice that none of the available formats is selected.
5) If you try to compare both files you'll get the warning about the different encodings.

BR

**Comment by xylographe** [comment] 2016-06-08 10:34
Hello Pavel,

I was unable to reproduce.
(3) I used the "Reload" menu-item from the tab context menu. After reloading the status bar does indeed (erroneously) report UNIX line endings.
(4) The "Encoding" menu and the status bar show UTF-8 (UTF-8-BOM) at all times.
(5) Compare is performed (correctly) without different-encodings warning.

I also tried with a windows-1252 encoded file, but the result was the same (obviously, Windows-1252 is shown instead of UTF-8-BOM).

**Comment by pnedev** [comment] 2016-06-08 14:21
Hello @xylographe ,

Hm, weird.
Thanks for trying anyway.
We'll come back to this some time in the future, when we are able to reproduce the issue.

BR

**Comment by pnedev** [comment] 2016-06-09 13:26
Hello @xylographe ,

The different encodings false report appeared again on my side.
I'm pretty sure it is connected to the N++ file reload functionality. This time I was using N++ reload command not the Reload plugin. Again, nothing is selected in the N++ Encoding menu.
That was just FYI.

Can you please try the following:

1) Open a file with ANSI encoding.
2) Look at the N++ Encoding menu - "Encode in ANSI" should be selected.
3) Just use N++ reload command to reload the file (_File / Reload from Disk_).
4) Check again the Encoding menu - "Encode in ANSI" is no longer selected.

That's when the problems with the seemingly wrong CP encodings warning start.
Thanks.

BR

**Comment by xylographe** [comment] 2016-06-09 17:40
Hello Pavel,

I saved some text in windows-1252 encoding.

1. After opening the file in NPP both status bar and Encoding menu report ANSI.
2. After "File > Reload from Disk" nothing has changed: "Encode in ANSI" is still selected, and the status bar shows "ANSI" too.
3. Remove a few lines.
4. "File > Reload from Disk" and confirm message box question.
5. "Encode in ANSI" is still selected, and status bar shows "ANSI".

To be sure I've repeated (3)(4) six times, and every time the result was (5).

Win7SP1[x64] + NPP 6.9.2
```
  Notepad++ v6.9.2
  Build time : May 18 2016 - 00:34:05
  Path : C:\Program Files (x86)\Notepad++\notepad++.exe
  Admin mode : OFF
  Local Conf mode : OFF
  OS : Windows 7
  Plugins : CodeAlignmentNpp.dll ComparePlugin.dll DSpellCheckOK.dll EmmetNPP.dll 
    Explorer.dll HexEditorOK.dll JSMinNPP.dll mimeTools.dll MultiClipboardOK.dll 
    NamedBookmarks.dll NppCalc.dll NppColumnSort.dll NppConverter.dll NppEditorConfig.dll 
    NppExec.dll NppExport.dll NppFTP.dll NppGist.dll NppSaveAsAdmin.dll NppTextFX.dll 
    NppToolBucket.dll PluginManager.dll PythonScript.dll ScrollPastEOFUni.dll 
    VisualStudioLineCopy.Unicode.dll 
```

**Comment by pnedev** [comment] 2016-06-10 07:13
Hello @xylographe ,

Thanks for testing and sharing the results.
Then the issue I'm observing must be related to Linux+Wine.
I'll try also on my Win7 computer but I suspect I'll get the same result as you.

BR

**Comment by pnedev** [comment] 2016-06-13 07:52
Hello @xylographe ,

I've checked the reload issue scenario on my Win7 machine and it is completely reproducible.

Could you try to open one of CP's source files (those are ANSI), let's say _NppHelpers.h_ for clarity.
Have a look at _Encoding_ menu.
Trigger _File -> Reload from Disk_.
Look again at _Encoding_ menu.

Is _Encode in ANSI_ still checked?

Thank you.

BR

**Comment by xylographe** [comment] 2016-06-13 08:52
Hello Pavel,

Following those 4 steps exactly I get the same result as you do : 
- (2) - *Encode in ANSI* is checked (also *ANSI* in status bar)
- (4) - *Encode in ANSI* is **not** checked (still *ANSI* in status bar)

It looks like this happens if the text file is ASCII encoded. My earlier test was performed with a 'real' ANSI file—French text (including non-ASCII characters) stored in windows-1252 encoding.

Perhaps you can try [this 'real' ANSI (windows-1252 encoding) example](https://www.dropbox.com/s/fut5d8105uwrawo/Xylographie.txt?dl=1), which gives me the results as described in [my previous comment](https://github.com/pnedev/compare-plugin/issues/74#issuecomment-224970774).

**Comment by pnedev** [comment] 2016-06-13 09:17
Hello @xylographe ,

Thank you for testing and writing back.
Testing with your file leads to the same results as you described earlier.

It looks like the problem with the seemingly wrong CP encoding warning is connected to the ASCII file reload N++ issue.

That was FYI, thanks again.

BR
