### ISSUE TITLE
Moved lines incorrectly classified

### ISSUE THREAD

**Issue by sjcoo** [pnedev/compare-plugin#162] opened 2018-04-18 23:59 UTC
I am seeing a few instances where moved lines are incorrectly identified as not present in the old file, unique to the new file.  Example: line 2 in the screenshot below.   "Detect Moves" is checked.  Context: Windows 10; Notepad++ v7.5.6 (32 bit); Compare Plugin v2.0.0.

![2018-04-18_npp_compare_detect_moves_error](https://user-images.githubusercontent.com/31407920/38963348-13cef60e-4337-11e8-854e-79f8796cf245.PNG)

**Comment by pnedev** [comment] 2018-04-19 09:05
Hello @sjcoo ,

Thanks for reporting the issue.
Just to clarify one thing: If a line is not marked as moved it does NOT necessarily mean it is unique (it can still be present in the other file).

BR

**Comment by FireReaver** [comment] 2018-05-25 16:22
I can confirm I have that issue too.
Very annoying tbh.
Strange how in the previous version of the plugin the move function worked as intended.

**Comment by sjcoo** [comment] 2018-05-25 19:17
pnedev: Thank you for your response.  The files you requested are attached.  Please excuse my delay in responding.    In my original post, I should have mentioned that both old and new files are shown in their entirety - just five lines in each file, meant to provide a simple, uncluttered example.

[file_old.txt](https://github.com/pnedev/compare-plugin/files/2040601/file_old.txt)
[file_new.txt](https://github.com/pnedev/compare-plugin/files/2040603/file_new.txt)

**Comment by Yaron10** [comment] 2018-05-25 20:20
Hello @sjcoo,

The issue should be fixed in a new CP version Pavel Nedev has been working on.

Best regards.
***
@FireReaver.

> Very annoying tbh.
Strange how in the previous version of the plugin the move function worked as intended.

We should thank Pavel Nedev for his hard work and the numerous improvements introduced in v2.

**Comment by sjcoo** [comment] 2018-05-26 05:40
Hello, @Yaron10 

Thank you for this update.  And I agree that Pavel Nedev deserves great thanks for the obvious and welcome improvements seen in v2.

**Comment by Yaron10** [comment] 2018-05-26 12:13
Hello @sjcoo,

> Thank you for this update.

You're welcome.

> And I agree that Pavel Nedev deserves great thanks for the obvious and welcome improvements seen in v2.

:+1:

**Comment by pnedev** [comment] 2018-05-28 08:56
Hello all,

Thank you @sjcoo and @Yaron10 :+1: 

I'll have a look at the issue.

BR

**Comment by pnedev** [comment] 2018-07-17 11:55
Hi all,

The issue is fixed in master branch.

BR

**Closed by pnedev** 2018-07-17 11:55 UTC
Labels: bug
