### ISSUE TITLE
Compare NavBar flickers continuously without Aero enabled

### ISSUE THREAD

**Issue by toasterking** [pnedev/compare-plugin#121] opened 2017-03-07 15:59 UTC
In Compare Plugin v2.0.0, when Aero is not enabled in Windows 7 and the Notepad++ window has focus, Compare NavBar flickers about every 300 ms.

**Comment by Yaron10** [comment] 2017-03-07 16:37
Hello @toasterking,

I'm using Windows 7 with the Classic Theme and I can't reproduce the flickering.
Can you please provide more details?
Which Notepad++ version are you using?

Thanks.

Best regards.

**Comment by pnedev** [comment] 2017-03-08 08:49
Hello @Yaron10 ,

Thanks for the support.

Hello @toasterking ,

I, as Yaron, could not reproduce such behavior. 

> Which Notepad++ version are you using?

Could you please provide that info?
Thanks.

BR

**Comment by Yaron10** [comment] 2017-03-08 16:30
Hello Pavel,

Thank you.

BR

**Comment by toasterking** [comment] 2017-03-10 01:27
Thank you for investigating my report.
I can reproduce with both the Windows 7 Basic theme and the Windows Classic theme.  Once the Compare NavBar appears, it flickers (visually repaints without double-buffering) about once every 300ms whilst Notepad++ is sitting idle.  I'm using Notepad++ 7.2.2 32-bit on Windows 7 Enterprise 32-bit.
I'm probably an odd case, though, because I am also using an old Intel video driver written for Windows XP because the driver intended for Windows 7 is incompatible with a PAE patch I'm using.  I'm also using MaxiVista drivers for extending displays over a network.  If you can't reproduce this with a more sane configuration, you should probably just disregard.  :-)
Thank you for all the recent improvements to the Compare plugin.  Your work is very much appreciated!

**Comment by pnedev** [comment] 2017-03-10 07:43
Hello @toasterking ,

Thanks for the details.
I cannot reproduce the issue you describe but I know that the NavBar occasionally flickers on Wine when you scroll fast its marker. I'll look into it some time soon to see if I can improve the performance.
Do you experience the same problem with other programs (if it is a video driver issue it should affect other applications as well)?

BR

**Comment by pnedev** [comment] 2018-07-18 15:07
Hello @toasterking ,

The flickering I have noticed is fixed in **[this x86 binary](https://ci.appveyor.com/api/buildjobs/5k02tpsuqdgr0grf/artifacts/ComparePlugin.dll)**.
I'm closing this ticket but feel free to write again here or in a new issue if you still experience the same problem.
Thanks.

BR

**Closed by pnedev** 2018-07-18 15:07 UTC
Labels: enhancement, question
