### ISSUE TITLE
"Close All" does not close all compared files

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#95] opened 2016-08-17 00:55 UTC
Hello Pavel,

The following issue is slightly illusive: I'm not sure all the steps in the following STR are necessary.

STR:
Start NPP.
Open A and B.
Compare (B is active).
Open C.
Activate A.
Open D.
Activate C.
Compare.
Activate A.
Close All.

Result:
D is open.

Thank you very much.
BR

**Comment by pnedev** [comment] 2016-08-17 08:00
Hello Yaron,

That is confirmed, thanks for reporting.

BR

**Comment by Yaron10** [comment] 2016-08-17 13:10
Hello Pavel,

Thank you. I appreciate your time and work.

BR

**Comment by pnedev** [comment] 2016-08-18 14:42
Hello Yaron,

Just FYI:

To reproduce the issue it is enough to:

1) Open A and B and compare them.
2) Switch to Sub-view and open file C there.
3) Close all.

BR

**Comment by Yaron10** [comment] 2016-08-18 23:56
Hello Pavel,

Indeed. That was a good catch. :)
Thanks again. I appreciate it.

BR

**Comment by Yaron10** [comment] 2016-08-20 22:01
Hello Pavel,

1) Have A and B in two views and compare them.
2) Switch to Sub-view and open file C there.
3) Close all.

Result:
All files are closed.

Thanks again.
Have a nice weekend.

**Comment by pnedev** [comment] 2016-08-22 08:08
Hello Yaron,

Thanks for the feedback. Perhaps it will help narrow down the possible causes for the issue. :+1: 

BR

**Comment by Yaron10** [comment] 2016-08-22 22:05
Hello Pavel,

I do hope so.
Thanks and best of luck.

**Comment by pnedev** [comment] 2016-09-13 14:06
Hello Yaron,

The issue is fixed.
Please note that some regressions are possible. This is because some refactoring was necessary.
If you come across something weird please report as always. Thanks.

BR

**Comment by Yaron10** [comment] 2016-09-13 23:54
Hello Pavel,

Great work! :+1: 
Thank you very much. I highly appreciate it.

All seems to work very well except for a minor regression. You may not think so but IMO it is important. :)

**STR 1:**
Start NPP.
Open two files.
Compare.
Close the file in the Main-View.

**STR 2:**
Start NPP.
Open two files.
Compare.
Activate the file in the Sub-View.
Close All.

**Result:**
The current view is Sub-View.
***
**A good result. :)**

**STR:**
Double-View.
Sub-View is active-focused.
Compare.
Files Match.
Close? - Yes.

**Result:**
The current view is Main-View.

Best regards.

**Comment by pnedev** [comment] 2016-09-14 10:54
Hello Yaron,

Well, I don't interfere the closing of files in any way.
If you simply open two files (A and B), move B to other view, focus on it and close all files then you will again end-up in Sub-View single mode.

The good result case you give as an example is different because I am closing the files myself on behalf of the user and thus I have control on the process.

Thanks for testing and commenting.

BR

**Comment by Yaron10** [comment] 2016-09-14 12:54
Hello Pavel,

> Well, I don't interfere the closing of files in any way.

As opposed to the previous implementation, correct?
In the two ("bad") cases I've mentioned we used to end up with Main-View.

> If you simply open two files (A and B), move B to other view, focus on it and close all files then you will again end-up in Sub-View single mode.

Indeed.
But as long as *the user doesn't use "Move to Other View" himself* it would be better if the default Main-View be preserved.
It's certainly important to my personal workflow.

Would implementing this be complex with the new handling of closing files?

Thank you. I appreciate your patience.

BR

**Comment by pnedev** [comment] 2016-09-15 09:05
Hello Yaron,

I've made some additions. Now if you close a compared file and only one file remains open (which is also the case when all files are closed) then you'll end-up in single main view.
Hope that fits your expectations.

BR

**Comment by Yaron10** [comment] 2016-09-15 20:07
Hello Pavel,

Great. Your work is always *beyond* my expectations. :)
Special thanks for that.

Allow me another comment.
I had a quick look a the code and it's really clever.
It causes, though, two issues:

**1)**
Start NPP.
Open two files.
Compare.
Activate the file in the Sub-View.
Close All.

Result:
The Compare margin is not removed and the Compare commands are enabled.
(And if you open a new doc you get double "New 1").

NOTE:
A) The behavior is not consistent; if it doesn't happen the first tine, please repeat the steps.
B) Prior to https://github.com/pnedev/compare-plugin/commit/50b7fad2b1fee1a2e5b9645dd7c9e261b0a358cd the Compare commands not being disabled already existed. 

**2) Minor - NPP Bug.**
Start NPP.
Open two files.
Compare.
Close the file in the Main-View.

Result:
The *open* file is in the Recent Files List.

This is a NPP bug (when using "Clone...").
If you find that using "Clone..." is shorter and more efficient, let it be.

Best regards.

**Comment by pnedev** [comment] 2016-09-16 00:02
Hello Yaron,

I'll have a look, thanks.

BR

**Comment by Yaron10** [comment] 2016-09-16 00:41
Hello Pavel,

Thank you. I appreciate your perseverance.

The "Compare commands not being disabled" issue often occurs even if you Close All when the Main-View is active-focused.

BR

**Comment by Yaron10** [comment] 2016-11-01 15:09
Hello Pavel,

The second from https://github.com/pnedev/compare-plugin/issues/89#issuecomment-257405459.

After comparing two files I frequently use "Close All" without "Clear Compare". 
Since the issue mentioned above ( (1) in https://github.com/pnedev/compare-plugin/issues/95#issuecomment-247438397 ) was introduced, I try to remember to "Clear Compare" and then "Close All". I often forget...

This issue is closed. I also don't know if you've already looked into it nor the degree of its complexity.
So I wanted to ask you if giving it a higher priority would disrupt your work. Please don't mind. :)

Thank you very much.
BR

**Comment by pnedev** [comment] 2016-11-28 09:14
Hello @Yaron10 ,

I'm not able to reproduce issue 1 at the moment except for the double _New 1_ when you open new file after _Close All_.
What do you mean by `Compare margin`? The place for the + / - marks next to the line number field?

BR

**Comment by pnedev** [comment] 2016-11-28 11:25
Hello again,

I have fixed the possible _New 1_ related issues.
Could you please try commit https://github.com/pnedev/compare-plugin/commit/c68f00074441b39695f740113b1ae052c2aa8e6f and tell me if you still see a problem?
You can find the corresponding plugin DLL here: https://ci.appveyor.com/api/buildjobs/uy6xp7vobefw3cy7/artifacts/ComparePlugin.Win32.Release%20Unicode.v140_xp.dll

Thanks.

BR

**Comment by Yaron10** [comment] 2016-11-28 16:35
Hello Pavel,

> What do you mean by Compare margin? The place for the + / - marks next to the line number field?

Indeed. The column/margin next to the line number margin (that's the term used in NPP Styler).

The behavior is not consistent but it's certainly reproducible. I encounter it quite frequently. 

Please try clearing the Recent Files list.
Start NPP.
Open two files.
Compare.
**Activate the file in the Sub-View.**
Close All.

If it still doesn't happen, please try opening the two files (now in the recent list) in a different order.

Thank you for looking into it. I do appreciate it. 
Been waiting for that. :)

The double "New 1" issue is fixed. Thanks.

***

Thank you also for fixing issue (2).
Opening a new file and closing it is better than cloning. Great. 👍 

BR

**Comment by pnedev** [comment] 2016-11-30 12:53
Hello Yaron,

Could you please test with latest master (https://github.com/pnedev/compare-plugin/commit/b7a1c430d476eed516580e69a38a76cbb1149626) and write back if the issue is fixed / still present?
Thanks.

BR

**Comment by Yaron10** [comment] 2016-11-30 15:15
Hello Pavel,

Some progress. :)
The Compare commands are correctly disabled now but the Compare margin is still there.

Did you manage to reproduce it?
If not - please close NPP, restart it and open the files from the Recent Files list (it also happens if you open them from Windows Explorer). 
It occurs on one out of three/four times.

Thank you very much. I appreciate it.
BR

**Comment by pnedev** [comment] 2016-11-30 16:09
Hello Yaron,

I'm not able to reproduce it on my Linux Wine setup.
Could you please try again the latest commit https://github.com/pnedev/compare-plugin/commit/4472247081fe99870055f42748921bb1ede6a1f6?
Thanks.

BR

**Comment by Yaron10** [comment] 2016-11-30 18:39
Hello Pavel,

Well done!
This seems to have fixed it (the minor reservation is due to the issue's elusiveness).
Special thanks. This is important to my workflow and I'm truly grateful. 

> I'm not able to reproduce it on my Linux Wine setup.

So you've fixed it blind-folded. :) 👍 

BR

**Closed** 2016-11-30 18:40 UTC
Labels: bug

**Comment by pnedev** [comment] 2016-12-01 08:37
Hello Yaron,

Great, thanks for testing.

BR

**Comment by Yaron10** [comment] 2016-12-01 17:03
Hello Pavel,

After testing it more thoroughly, I retract the minor reservation. :)
Great work. Many thanks again.

BR

**Comment by pnedev** [comment] 2016-12-02 08:17
Great :)

BR
