### ISSUE TITLE
A file is closed when comparing two empty files. 

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#25] opened 2016-03-22 17:55 UTC
Start NPP.
Open 2 new empty files.
Compare.

Result:
The second file is closed.

**Comment by pnedev** [comment] 2016-03-23 08:22
Confirmed, thanks.

BR

**Comment by Yaron10** [comment] 2016-03-23 21:21
Thank you.

BR

**Comment by pnedev** [comment] 2016-04-07 10:25
Hello Yaron,

If 2 new empty files are opened and compared the second file is not closed.

If you start Notepad++ it has initial 'New 1' empty file. If you open new empty file ('New 2') and compare, 'New 2' is closed. If you start the compare from 'New 1' then it is closed.
It seems to be a bug in Notepad++ initial 'New 1' file / buffer handling - there is nothing I can do about it from the plugin itself so I'm closing this issue as irrelevant to the plugin.

BR

**Closed by pnedev** 2016-04-07 10:25 UTC
Labels: bug

**Comment by Yaron10** [comment] 2016-04-08 14:29
Hello Pavel,

Thanks for the explanation.
How about marking it as a (minor) Known Issue?

Best regards.

**Comment by pnedev** [comment] 2016-04-08 15:45
Hi Yaron,

If you know how to do this, can you explain briefly?
Thanks.

BR

**Comment by Yaron10** [comment] 2016-04-08 20:30
Hello Pavel,

I meant marking it in your notes so that you would remember to mention it in the Changelog. :)
I'll add it to my notes.

BR

**Comment by pnedev** [comment] 2016-04-08 23:59
Aha, I see :)
I'll surely miss something when I get to the Changelog ;)
Thanks Yaron.

BR

**Comment by Yaron10** [comment] 2016-04-09 14:57
Hello Pavel,

Sorry for the confusion. :)

BR

**Comment by pnedev** [comment] 2016-04-12 15:57
Hello Yaron,

I've made a workaround for this in master branch. It is not observed anymore.

BR

**Comment by Yaron10** [comment] 2016-04-13 02:53
Hello Pavel,

You're the best. :+1: 
Thank you.

BR
