### ISSUE TITLE
Sometimes modified text disappears when saving

### ISSUE THREAD

**Issue by niente0** [pnedev/compare-plugin#256] opened 2021-01-18 12:00 UTC
**Sometimes modified text disappears when saving.**

As an example, I attach 2 files: "first.asp" and "second.asp".
1. Compare first to second
2. Add the missing "end if" in second file to make it identical to the first file
3. Click on "save"

Result: the "end if" DISAPPEARS.
Please fix!
Thank you

Attachment: [example.zip](https://github.com/pnedev/compare-plugin/files/5830044/example.zip)

**Comment by pnedev** [comment] 2021-01-18 23:29
Hello @niente0 ,

I couldn't reproduce your issue with Compare plugin v2.0.1 in Notepad++ v7.9.1.
What are the Notepad++ and Compare plugin versions on your side ?

**Comment by pnedev** [comment] 2021-01-18 23:53
Hi again @niente0 ,

I think I understand now.
You are using Compare plugin v2.0 (or v2.0.1 , doesn't really matter) and you are entering the missing text in the gray line, correct? After the file save the entered text in the gray line disappears, yes?

**Comment by niente0** [comment] 2021-01-21 12:39
Yes, exactly. If I enter the missing text outside the grey line it works, while inside it disappears.
I think there could be 2 solutions:
1. accept the text entered into the grey line
2. prevent the user from entering text in the gray line

Thank you!

btw I'm using v2.0.1 with Notepad++ v7.9.1

**Comment by pnedev** [comment] 2021-01-21 23:24
Thank you for the reply @niente0 and for filing this issue.

Unfortunately I have stopped supporting ComparePlugin.
The good news is that I have almost finished a new comparing plugin I've been working on for quite some time - ComparePlus.
It is based on Compare plugin but is significantly enhanced and improved. It doesn't have the problem you describe.
I just hope I'll be able to finally make its first official release some time soon.

I will flag this issue as 'fixed' because of the above reasons (it is not present in ComparePlus that is almost released). This is to avoid future confusion on my side.

**Comment by pnedev** [comment] 2022-07-17 12:03
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.

**Closed by pnedev** 2022-07-17 12:03 UTC
Labels: fixed
