### ISSUE TITLE
[Enhancement] Change "First" background color

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#63] opened 2016-05-12 22:31 UTC
Hello Pavel,

How about setting a special background color for the tab selected as First?
For a later stage. :)

May I ask what your current triage is?
For my personal use I find issue https://github.com/pnedev/compare-plugin/issues/39 highly important.

Thank you.
BR

**Comment by pnedev** [comment] 2016-05-13 07:58
Hello Yaron,

That's a great suggestion, thank you :)

As a matter of fact since the initial idea of "Set first" came to my mind I've been thinking of implementing some visual cue marking the selected file but I haven't mentioned it so far because it is something I really don't now how to implement at the moment and I didn't want to make promises I may not fulfill.

So yes, I have that in mind and I'll keep this issue open as a reminder but I don't promise anything.
It is really something for the far future.

I consider #39 a low priority related to other issues.
I worked on it a couple of weeks ago thinking it would be a quick fix but I'm not quite sure at the moment how exactly to do it. This is because I haven't found a way yet to get a handle to the N++ toolbar.

BR

**Comment by Yaron10** [comment] 2016-05-13 13:40
Hello Pavel,

Thank you. For the far future. :)

Regarding https://github.com/pnedev/compare-plugin/issues/39:
If you only use the toolbar buttons it might be a serious issue.
Anyway - when you get to it, how about writing to Dave (Customize Toolbar Author)?
I've asked him to fix some issues and he's been very kind.

BR

**Comment by pnedev** [comment] 2016-05-13 14:40
Hello Yaron,

Writing to Dave is a good idea. I was looking for the Customize Toolbar's source to use it as a reference but couldn't find it.
Thanks.

BR

**Comment by Yaron10** [comment] 2016-05-13 20:13
Hello Pavel,

I think CT is not open-source.
Thank you and best of luck.

BR

**Comment by pnedev** [comment] 2016-05-17 22:31
Hello Yaron,

I added a visual cue showing the manually set first file - the tab name is changed accordingly.

BR

**Comment by Yaron10** [comment] 2016-05-18 00:42
Hello Pavel,

Absolutely brilliant! :+1: 
Old/New according to the setting. I was really impressed.
Thank you so much.

*Please don't consider the following comment ungrateful. Just a minor known issue for the record. :)*

In a RTL interface a file named `(prefs).js` is displayed like [this](http://s32.postimg.org/b46g4ksxx/Parenthesis.png) in NPP.
So I've changed the code to `TEXT(" ** Old to Compare") : TEXT(" ** New to Compare"));`.
This isn't a good solution if the file name contains RTL characters.

Best regards.

**Comment by xylographe** [comment] 2016-05-18 01:27
Hello Yaron,

```
TEXT(" \u200E(Old to Compare)") : TEXT(" \u200E(New to Compare)")
```
U+200E is the "LEFT-TO-RIGHT MARK".

**Comment by xylographe** [comment] 2016-05-18 01:49
Hello Pavel,

Great feature. Thank you.

I did shorten the text a ‘little’ : **`TEXT(" \u200E\u24B7") : TEXT(" \u200E\u24BB")`**  :wink:

**Comment by pnedev** [comment] 2016-05-18 07:17
Hello @Yaron10 , @xylographe ,

I don't have experience with RTL and couldn't quite understand that:

> In a RTL interface a file named (prefs).js is displayed like this in NPP.
So I've changed the code to TEXT(" ** Old to Compare") : TEXT(" ** New to Compare"));.
This isn't a good solution if the file name contains RTL characters.

You'll help me save some time if you suggest how to change the "set first" string mark so both LTR and RTL appear OK.
Thanks.

BR

**Comment by xylographe** [comment] 2016-05-18 13:29
Tested with Hebrew file name, no problem.

![cp-rtl](https://cloud.githubusercontent.com/assets/8535293/15360176/e0494606-1d0c-11e6-8db9-e90723a21573.png)

**Comment by xylographe** [comment] 2016-05-18 13:40
Hello Pavel,

[Wikipedia](https://en.wikipedia.org/wiki/Bi-directional_text) has a human readable article on bi-directional text. Note the division in strong, weak and neutral characters. The LTR or RTL mark immediately after a neutral character can often be used to correct problems, but it doesn't seem necessary here. (? @Yaron10 ?).

**Comment by Yaron10** [comment] 2016-05-18 13:50
Hello Pavel and xylographe,

xylographe,
Thanks for suggesting `TEXT(" \u200E(Old to Compare)") : TEXT(" \u200E(New to Compare)")` and for the testing. I appreciate that.
Your screenshot is a LTR interface with a Hebrew file name.
Could you change the interface language to Hebrew, restart NPP and test again?
It would be great if you find a solution to that.

Pavel,
The current implementation is great.
By "This isn't a good solution if the file name contains RTL characters." I meant that **my** change doesn't help in that case.

If you think that `TEXT(" ** Old to Compare") : TEXT(" ** New to Compare"));` is as good as parenthesis, it would be better for a RTL interface in most cases.
I'm not objective now. :)

xylographe posted as I was typing. :) Let's wait a bit.

Best regards.

**Comment by xylographe** [comment] 2016-05-18 14:20
Hello Yaron,

Everything seems OK in Hebrew locale?

![cp-rtl2](https://cloud.githubusercontent.com/assets/8535293/15362048/24745fee-1d14-11e6-9f2c-833cbfaf20bc.png)

**Comment by pnedev** [comment] 2016-05-18 14:24
Hello Yaron,

Please test https://github.com/pnedev/compare-plugin/commit/1f1770c2a52e23ee6f9bb9b0fac1c15e75b56eb5 and tell me if it works for you.
If it is OK I'll merge it to master.
Thanks.

BR

**Comment by xylographe** [comment] 2016-05-18 14:28
Hello Yaron,

But this one (**with RTL mark**) is wrong,

![cp-rtl3](https://cloud.githubusercontent.com/assets/8535293/15362284/0cfcc9d6-1d15-11e6-8f51-729caa0eab03.png)

Could you post an example pic where the original TEXT doesn't work?

**Comment by xylographe** [comment] 2016-05-18 15:08
Hello Pavel,

Result from rtl* branch,

![cp-rtl4](https://cloud.githubusercontent.com/assets/8535293/15363950/dfd48718-1d1a-11e6-8c20-c4249aa932ca.png)

The "(New to Compare)" is now shown **before** the file name?

**Comment by pnedev** [comment] 2016-05-18 15:12
Hello @xylographe ,

Then current master should be OK,
Thanks for testing this.

BR

**Comment by Yaron10** [comment] 2016-05-18 15:16
Hello gentlemen,

Thank you. I do appreciate it.

Unfortunately https://github.com/pnedev/compare-plugin/commit/1f1770c2a52e23ee6f9bb9b0fac1c15e75b56eb5 doesn't make a difference.

Using a parenthesis, there's no problem if the file name is Hebrew.
If the file name is English, [this](http://s32.postimg.org/e3wglb3t1/image.png) is the result.

Mixing LTR and RTL is notoriously complex.

BR

**Comment by xylographe** [comment] 2016-05-18 15:26
Thank you, Yaron. Now I see what you mean.
Reproduced with a file named `hello (goodbye).java` :  (rtl* branch)

![cp-rtl5](https://cloud.githubusercontent.com/assets/8535293/15364648/862a3962-1d1d-11e6-92cf-115288759079.png)

**Comment by pnedev** [comment] 2016-05-18 15:39
Thanks for clarifying Yaron.

Well, what shall we do then? Don't use parenthesis?
What do you think?

BR

**Comment by xylographe** [comment] 2016-05-18 16:35
Hello Pavel,

Let's not throw in the towel too soon : 

![cp-rtl6](https://cloud.githubusercontent.com/assets/8535293/15366887/cad47e34-1d26-11e6-8d14-123fb9042479.png)

Obviously, this is not the **right** solution (too many marks), but it shows that it can be fixed.

**Comment by Yaron10** [comment] 2016-05-18 16:52
Hello Pavel and xylographe,

Thanks again. I appreciate it.

RTL users are used to those quirks.
I really added that comment just for the record.

xylographe,
That's nice. Does it work for a Hebrew file name as well?

Pavel,
Please let's wait for xylographe's reply.

BR

**Comment by xylographe** [comment] 2016-05-18 17:09
This works for Latin and Hebrew file names :  (using master branch, only these two lines changed)
```
_sntprintf_s(tabText, _countof(tabText), _TRUNCATE, TEXT("%s \u200E%s"),
_firstTabText, Settings.OldFileIsFirst ? TEXT("(\u200EOld to Compare)\u200E") : TEXT("(\u200ENew to Compare)\u200E"));
```
Sorry, Pavel, but all these LTR marks are an absolute necessity. Leave one of them out, and the parens will be wrong in either the Latin or the Hebrew script file name.

Hebrew file name,

![cp-rtl7](https://cloud.githubusercontent.com/assets/8535293/15367904/5c0725d8-1d2b-11e6-98d6-16765c1d1572.png)

Latin file name,

![cp-rtl8](https://cloud.githubusercontent.com/assets/8535293/15367924/783e9876-1d2b-11e6-869b-a6d976f758a8.png)

**Comment by xylographe** [comment] 2016-05-18 17:22
Perhaps, slightly more legible,
```
_sntprintf_s(tabText, _countof(tabText), _TRUNCATE, TEXT("%s \u200E(\u200E%s)\u200E"),
    _firstTabText, Settings.OldFileIsFirst ? TEXT("Old to Compare") : TEXT("New to Compare"));
```

**Comment by Yaron10** [comment] 2016-05-18 17:46
Hello xylographe,

Thank you very much. :+1: 
I really appreciate it.

If the file name is Hebrew and the extension is Latin there's still a minor issue.
Could you please try it?

Pavel,
That's really nice, isn't it?

BR

**Comment by xylographe** [comment] 2016-05-18 18:26
Hello Yaron,

Mixed file name, that's a tough one, :)
How should this be displayed?
Perhaps, `(Old to Compare) txt.כללי `? Or different?

**Comment by Yaron10** [comment] 2016-05-18 19:02
Hello xylographe,

Being aware of the LTR/RTL complexity, I actually didn't think you'd be able to achieve what you have.
So if it's too tough, just leave it. :)

If you continue trying, your pattern is correct; you start with the file name from the right.

Thanks again.
BR

**Comment by xylographe** [comment] 2016-05-18 21:23
"When the going gets tough, the tough get going" :)

As I wrote some time ago in another issue, I'm almost 100% visually left-to-right oriented. That was the real problem here. I was thinking LTR i/o RTL. Anyway, after closer examining the RTL 'world' in NPP the penny finally dropped. We don't need three LTR marks in an RTL environment, we need two RTL marks and only one LTR mark, like this: 

```cpp
const bool isRTL = (0 != (::GetWindowLongPtr(nppData._nppHandle, GWL_EXSTYLE) & WS_EX_LAYOUTRTL));

if (isRTL)
    _sntprintf_s(tabText, _countof(tabText), _TRUNCATE, TEXT("%s\u2000\u200F(\u200E%s to Compare)\u200F"),
        _firstTabText, Settings.OldFileIsFirst ? TEXT("Old") : TEXT("New"));
 else
    _sntprintf_s(tabText, _countof(tabText), _TRUNCATE, TEXT("%s (%s to Compare)"),
        _firstTabText, Settings.OldFileIsFirst ? TEXT("Old") : TEXT("New"));
```
Note that these marks wouldn't work in the LTR 'universe', hence the `isRTL` var from Pavel's *rtl_mark* branch is back. Also, I use en space (U+2000) i/o normal space, because with normal space the RTL opening parenthesis is IMO to close to the preceding letter.

Result:

![cp-rtl9](https://cloud.githubusercontent.com/assets/8535293/15375383/14aee8be-1d4f-11e6-9de2-dd27b9b16b23.png)

Tested with Latin script file name, Hebrew script file name, Hebrew name with Latin extension, and Latin name with Hebrew extension.

**Comment by Yaron10** [comment] 2016-05-18 22:36
Hello xylographe,

Thanks again. I do appreciate it.

Now that you've achieved this great result, allow me one more question:
Hebrew name with Latin extension is excellent.
Latin name with Latin extension looked like [this](http://s32.postimg.org/tsy8762kl/Prev.png) in your previous version, and [this](http://s32.postimg.org/obxnd6wlh/Current.png) is how it's displayed now.
I may have mislead you as to the right pattern: `(Old to Compare) txt.כללי` is correct, but in Latin `prefs.js (Old to Compare)` is better as I automatically switch to LTR mode (mentally) and I see it as you do. :)

Is that possible?
***
Hello Pavel,

Thanks again for the `const bool isRTL` part. As always, I highly appreciate it. :) 

BR

**Comment by xylographe** [comment] 2016-05-19 00:28
Hello Yaron,

> `(Old to Compare) txt.כללי` is correct, but in Latin `prefs.js (Old to Compare)` is better

I'm afraid you cannot have them both,

(1) `prefs.js (Old to Compare)` implies `txt (Old to Compare).כללי`

(2) `(Old to Compare) txt.כללי` implies `(Old to Compare) prefs.js`

When the preceding character is a strong LTR character (e.g., a Latin script letter), the `(Old to Compare)` must be either LTR (1) or RTL (2). We, humans, can easily see the full file name context, but the bidi algorithm uses only a very limited context (based on the types of individual characters).

**Comment by Yaron10** [comment] 2016-05-19 00:55
Hello xylographe,

Thank you very much for the research and the explanation.

Well, you can't always get what you want. :)
I'll think about it tomorrow.

Best regards.

**Comment by pnedev** [comment] 2016-05-19 08:34
Hello guys,

Good job @xylographe , thanks for the research and testing :+1: 

What about isolates? Wouldn't they accomplish just what we need?
For example can someone test this https://github.com/pnedev/compare-plugin/commit/b7e7055dbfe68820a263cffc1e8928af67f34583?

Unfortunately my work machine is on Linux and my cross-compiler is currently not dealing well with Unicode BiDi characters (or perhaps Wine is the problem, I cannot tell for sure) so I cannot test my changes myself.

Thanks.

BR

**Comment by xylographe** [comment] 2016-05-19 08:50
Hello Pavel,

Unfortunately, isolates are not supported.
Result with rtl_mark2 branch : 

![cp-rtl2](https://cloud.githubusercontent.com/assets/8535293/15387641/7725d1f6-1dae-11e6-93fd-5ba51bf1093f.png)

The two rectangles are the isolates. They are not recognised as bidi control characters.

**Comment by pnedev** [comment] 2016-05-19 08:58
Hello @xylographe ,

> Unfortunately, isolates are not supported.

That's bad.
Thanks for testing.

Isn't then better to use '<' and '>' for braces instead of '(' and ')'?
Are '<' and '>' BiDi neutral chars?

BR

**Comment by xylographe** [comment] 2016-05-19 09:13
Master branch, replaced `()` with `<>`
```
			_tcscpy_s(tabText, _countof(tabText), _firstTabText);
			_tcscat_s(tabText, _countof(tabText), Settings.OldFileIsFirst ?
					TEXT(" <Old to Compare>") : TEXT(" <New to Compare>"));
```
Result in RTL environment (Hebrew locale),

![cp-rtl3](https://cloud.githubusercontent.com/assets/8535293/15388361/e2d73d88-1db1-11e6-82a3-2709de99bd59.png)

![cp-rtl4](https://cloud.githubusercontent.com/assets/8535293/15388506/8fc6a7b8-1db2-11e6-9664-d2c64dad65d6.png)

Same problem as with parentheses. :(

**Comment by xylographe** [comment] 2016-05-19 09:29
Hello Pavel, 

> `(Old to Compare) txt.כללי` is correct, but in Latin `prefs.js (Old to Compare)` is better

To make `Old to Compare` act as RTL in one case, and act is LTR in the other case would require a file name parser, detecting if the name does or does not contain strong RTL characters. If it does not `Old to Compare` behaves LTR (prefs.js), otherwise it behaves RTL (txt.כללי).

But IMO this solution amounts to overkill.

**Comment by pnedev** [comment] 2016-05-19 10:15
Hello @xylographe ,

Thanks again for testing.
I suppose you are right. I cannot think of other way to solve this.
It seems that, as you are saying, tab name parsing is needed to make it work in all cases.

But it seems checking for RTL strong character presence in a string is not an easy task.

BR

**Comment by xylographe** [comment] 2016-05-19 11:52
Hello Pavel,

(A) The good news: I got rid of the LTR mark, leaving only the two RTL marks.

```cpp
const bool isRTL = (0 != (::GetWindowLongPtr(nppData._nppHandle, GWL_EXSTYLE) & WS_EX_LAYOUTRTL));

if (isRTL)
	_sntprintf_s(tabText, _countof(tabText), _TRUNCATE, TEXT("%s (\u200F%s to Compare)\u200F"),
		_firstTabText, Settings.OldFileIsFirst ? TEXT("Old") : TEXT("New"));
else
	_sntprintf_s(tabText, _countof(tabText), _TRUNCATE, TEXT("%s (%s to Compare)"),
		_firstTabText, Settings.OldFileIsFirst ? TEXT("Old") : TEXT("New"));
```

(B) Tab name parsing might be even more complicated than it appears at first sight. Let's consider two simple examples. Each `<L>` represents a Latin script word, each `<H>` represents a Hebrew script word.

(1) `<L> (<H>).cpp`
(2) `<H> (<L>).cpp`

(1) should probably (? @Yaron10 ?) be displayed **`<L> (<H>).cpp  (New to Compare)`** (LTR)
(2) should probably (? @Yaron10 ?) be displayed **`(New to Compare)  cpp.(<L>) <H>`** (RTL)

Our hypothetical tab name parser needs to break input into tokens, assigning a directional value to each token, depending on its position, brackets, hyphens/dashes, and (most likely) lots of other stuff. You would have to become an expert on RTL before you could implement it. :)

**Comment by Yaron10** [comment] 2016-05-19 15:18
Hello Pavel and xylographe, 

Thank you both again.

Before we return to the RTL discussion, here is a related bug.

STR:
Open two files.
Set First.
Switch to the other file.
Set First.
Close the current file.

Result:
The remaining file gets the closed file's name. 

*

Assuming this is fixed, back to LTR/RTL.

As I've mentioned before, RTL users are used to these issues. Especially in NPP which doesn't fully support bidi.
So parsing the file name is definitely not worth it.  

Myself and most probably other CP-RTL users would rather have Latin files displayed *perfectly* even at the cost of mixed files displayed wrongly.

So we should use one of xylographe's first suggestions:
`_sntprintf_s(tabText, _countof(tabText), _TRUNCATE, TEXT("%s \u200E(\u200E%s)\u200E"),
    _firstTabText, Settings.OldFileIsFirst ? TEXT("Old to Compare") : TEXT("New to Compare"));`

Or - now that I'm objective :) - what do you think about `TEXT(" ** Old to Compare") : TEXT(" ** New to Compare"));`? Could you please try it?
Asterisks are often used as "pay-attention" characters. 

Best regards.

**Comment by pnedev** [comment] 2016-05-19 16:18
Hello @xylographe ,

Thanks again. Yes, the RTL issue is a tough one :)

Hello @Yaron10 ,

Thanks for catching the issue with closing the first set file.
I fixed it in the latest master commit.
I also fixed some other possible issues with closing the file - when files on the left are closed and then the first set.
Parenthesis are changed to '**' mark - that is OK for me. Just tell me how it looks with different files (RTL, LTR + mixed).
@xylographe , how do you find '**'?

BR

**Comment by Yaron10** [comment] 2016-05-19 18:45
Hello Pavel,

Thank you very much for the quick fix.
A new minor issue.

STR:
Open two files.
Set First.
Switch to the other file.
Set First.
Close the current file.
Set First.

Result:
The navigation commands/buttons are enabled. 
***
Thanks also for the Asterisks.
LTR files are displayed properly.
Mixed files are displayed wrongly (we're used to it).
RTL characters are very rarely used for file-extensions. 

This is a truly great feature!

BR

**Comment by xylographe** [comment] 2016-05-19 19:17
Hello Pavel,

With **` ** `** in French locale all 4 file name types display as expected (i.e. LTR).

Results in Hebrew locale : 

(1) 100% Latin script == OK (LTR)
![cp-rtl1](https://cloud.githubusercontent.com/assets/8535293/15405712/4cedab5c-1e03-11e6-97ec-5bede2bd9f66.png)

(2) 100% Hebrew script == OK (RTL)
![cp-rtl2](https://cloud.githubusercontent.com/assets/8535293/15405802/c84c7d78-1e03-11e6-88ba-50e4a27d33ac.png)

(3) Latin name with Hebrew extension == OK (**html** is the name, not the extension :) )
![cp-rtl4](https://cloud.githubusercontent.com/assets/8535293/15405841/feacf0e6-1e03-11e6-8d68-f4d6a8a46417.png)

(4) Hebrew name with Latin extension == WRONG
![cp-rtl3](https://cloud.githubusercontent.com/assets/8535293/15405818/e8ec4590-1e03-11e6-8105-9fc884222a01.png)

I think the gibberish in (4) needs to be fixed (`New to Compare ** html.צור קשר`).

**Comment by Yaron10** [comment] 2016-05-19 19:39
Hello xylographe,

Thanks again.

> I think the gibberish in (4) needs to be fixed (New to Compare ** html.צור קשר).

I'd love to get it fixed. How? :)
As you've written it's either this or Latin.

BR

**Comment by xylographe** [comment] 2016-05-19 20:55
Hello Yaron,

I see, there's a slight misunderstanding.
I expected the **` ** `** would fix all display problems. Unfortunately, it doesn't.
Seems like we[1] will have to learn to live with it. :(

[1] Of course, the *we* is actually *you*, because *I* do not normally use an RTL locale. :)

**Comment by Yaron10** [comment] 2016-05-19 21:31
Hello xylographe,

Thanks for the clarification.

I suggested to use your

`_sntprintf_s(tabText, _countof(tabText), _TRUNCATE, TEXT("%s \u200E(\u200E%s)\u200E"), _firstTabText, Settings.OldFileIsFirst ? TEXT("Old to Compare") : TEXT("New to Compare"));`

or `TEXT(" ** Old to Compare") : TEXT(" ** New to Compare"));`.

Both are good for Latin and not for mixed files.

I just thought `**` might be slightly more prominent.

> [1] Of course, this we is actually you, because I do not normally use an RTL locale. :)

Yes, I assumed so. :)
This makes your good research more appreciated. Thanks.

BR

**Comment by pnedev** [comment] 2016-05-20 08:14
Hello guys,

@Yaron10 

> STR:
Open two files.
Set First.
Switch to the other file.
Set First.
Close the current file.
Set First.
Result:
The navigation commands/buttons are enabled.

I couldn't reproduce this. Could you elaborate more please? Thanks.

@xylographe ,

Thanks for testing again. :+1: 

Then we'll keep the `**` marking, thank you both.

BR

**Comment by Yaron10** [comment] 2016-05-20 12:14
Hello Pavel,

I tried to reproduce it again and it wouldn't. :)
Well, after some more tests:

**Clear the Recently Closed Files List or have only two files there.** 
Open two files.
Set First.
Switch to the other file.
Set First.
Close the current file.
Set First.

Result:
The navigation commands/buttons are enabled. 

Thank you.
BR

**Comment by pnedev** [comment] 2016-05-20 14:37
Hello Yaron,

Ah, again this "Recently closed files" list... :)
Could you please put this issue in the "Known problems" section?
I may look at it some time in the future but for now I don't have time to do so.
There are other more urgent tasks pending.
Thank you.

BR

**Closed by pnedev** 2016-05-20 14:37 UTC
Labels: enhancement

**Comment by Yaron10** [comment] 2016-05-20 20:12
Hello Pavel,

This is reproducible if you download a fresh NPP portable copy, install CP and open two files.

Thank you.
BR
