### ISSUE TITLE
NavBar re-opens unexpectedly

### ISSUE THREAD

**Issue by xylographe** [pnedev/compare-plugin#32] opened 2016-04-06 18:00 UTC
CP c1989be032b54c12578795489fce04d137e6a8ed
NPP 6.9.1
Win7 SP1 [64]

After closing NavBar and then switching focus to other view, NavBar re-opens.

Reproduce 1:
- compare two files
- set focus to left view
- close NavBar (⌧)
- click in right view

NavBar re-opens

Reproduce 2:
- compare two files
- set focus to right view
- close NavBar (⌧)
- click in left view

NavBar re-opens

**Comment by xylographe** [comment] 2016-04-06 18:12
Just noticed that closing NavBar does not change **Plugins > Compare > Navigation Bar** status (check box).

**Comment by pnedev** [comment] 2016-04-06 23:11
Hello xylographe,

Confirmed, thanks for reporting.
You noticed correctly -> this is exactly the reason it keeps reappearing. I'll fix that some time soon.

BR

**Comment by pnedev** [comment] 2016-04-07 15:07
Fixed in master branch, thanks.

BR

**Closed by pnedev** 2016-04-07 15:07 UTC
Labels: bug

**Comment by xylographe** [comment] 2016-04-09 06:12
Confirmed (CP 41d35747af3b0342d79ca4fb82c863e1f7c2d3fe).

Thank you, Pavel.
