### ISSUE TITLE
Exeption

### ISSUE THREAD

**Issue by amspeople** [pnedev/compare-plugin#192] opened 2019-03-05 20:36 UTC
When scrolling the file after comparison, I get an error as in the screenshot. The last version.
![2019-3-5 23-33-48](https://user-images.githubusercontent.com/5773978/53835859-7feb7c80-3f9f-11e9-893c-472f8dc8bdba.png)

**Comment by pnedev** [comment] 2019-03-06 08:42
Hello @amspeople ,

Do you have DSpellCheck plugin installed?
It causes such errors occasionally. If you have it, try disabling its automatic checking from the menu or temporarily remove it.

**Comment by amspeople** [comment] 2019-03-06 08:46
OK. I will write to you about the results.

**Comment by pnedev** [comment] 2019-03-08 14:07
Closing this issue as invalid (it is caused by DSpellCheck plugin).
Please write again if you believe it is Compare issue, thanks.

**Closed by pnedev** 2019-03-08 14:07 UTC
Labels: invalid, question
