### ISSUE TITLE
Match failure (partial failure)

### ISSUE THREAD

**Issue by marcofbbr** [pnedev/compare-plugin#254] opened 2020-12-02 15:07 UTC
Hi,
comparing two tabs I have an inconsistent results when I move the line somewhere else in the file.
Please have a look at the following snapshots. I am focusing on a specific entry that is highlighted in the text.
The \n character has been replaced in both file. 

All the notes below refers to the left frame. (the pictures have been added below as well)
-working case  `https://pasteboard.co/JD4z1TR.jpg`  Note: before and after the specified text, I have matching entries
-working case2 `https://pasteboard.co/JD4BtMt.jpg`  Note: before the text I added an empty line return, otherwise the match would have failed (see not working case 1)
-not working  case1 `https://pasteboard.co/JD4BO1z.jpg`  Note: the line above the specified text I have a matching text with a blue arrow 
-not working case2 `https://pasteboard.co/JD4Fjea.jpg` Note: the line above the specified text I have a matching text with a blue arrow (different location from previous example)

Notepad++ version: 7.5.1 64 bit
Compare plugin version: 2.0.0
[right panel.txt](https://github.com/pnedev/compare-plugin/files/5630284/right.panel.txt)
[left panel.txt](https://github.com/pnedev/compare-plugin/files/5630285/left.panel.txt)

working case
![Capture-working1](https://user-images.githubusercontent.com/30522516/100892869-0f96c580-34bb-11eb-804d-e99745f22ac3.JPG)
working case2
![Capture-working2](https://user-images.githubusercontent.com/30522516/100892866-0f96c580-34bb-11eb-86f3-1510f4d31c29.JPG)
not working case 1
![Capture-not_working1](https://user-images.githubusercontent.com/30522516/100892864-0efe2f00-34bb-11eb-9b45-e72f40aac2c4.JPG)
not working case2
![Capture-not_working2](https://user-images.githubusercontent.com/30522516/100892860-0c9bd500-34bb-11eb-8e0f-8d1537ba0f86.JPG)

**Comment by pnedev** [comment] 2020-12-07 23:23
Hi @marcofbbr ,

Thanks for filing this issue and sorry for my late reply.

I have stopped working on Compare plugin and it is currently not supported.
It has some issues with moved lines detection so probably this is what you have actually hit.

The good news is that I've been working quite some time now on a new plugin - ComparePlus that is Compare plugin successor but very enhanced one. It has also improved moved section detection. It is still not released yet but I hope it will be soon.
If you like I'll leave this issue open and I'll let you know here when ComparePlus is out so you can try your use case again.

BR

**Comment by pnedev** [comment] 2022-07-19 14:51
Hello @marcofbbr ,

Sorry for the late update but I couldn't find time and focus for this project for the last couple of years.

Now I'm close to releasing ComparePlus - the new plugin I wrote you about. It should be ready in a month or less and you could get it from the PluginAdmin panel in the next Notepad++ releases (after v8.4.4).
I tested the files you supplied here and those are properly marked by ComparePlus so the issue is no longer present. Thus I will close this thread now but if you encounter the same (or different) problem in ComparePlus in the future please file another issue regarding that.
Thanks a lot.

BR

**Closed by pnedev** 2022-07-19 14:51 UTC
Labels: bug, fixed
