### ISSUE TITLE
Diff Marks are not cleared after "Move to Other View"

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#38] opened 2016-04-08 06:28 UTC
Hello Pavel,

STR:

Compare.
Move to Other View.

Result:

The Diff Marks are not cleared in the other file.

I wonder why. Isn't a Close message sent when "Move to Other View" is executed?

Thank you.

BR

**Comment by pnedev** [comment] 2016-04-09 23:38
Hello Yaron,

Yes, I know about that issue and I think its root cause is the same as in [this](https://github.com/pnedev/compare-plugin/issues/34) issue.
I'll definitely investigate that further, thanks for reporting.

BR

**Comment by Yaron10** [comment] 2016-04-10 11:08
Thank you. I appreciate that.

BR

**Comment by pnedev** [comment] 2016-05-11 14:23
Fixed in latest master branch commit. Thanks.

BR

**Closed by pnedev** 2016-05-11 14:23 UTC
Labels: bug

**Comment by Yaron10** [comment] 2016-05-11 22:53
Hello Pavel,

Very nice. :+1: 
Thank you.

BR
