### ISSUE TITLE
Some issues when closing unsaved matched files

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#106] opened 2017-02-02 18:36 UTC
Hello Pavel,

I've just come across an interesting behavior.

STR:
Compare two identical files (file A is saved, file B is unsaved). 
Close compared files? - Yes.

Result:
The Save dialog shows up.
The "Only one file opened." message shows up.

If both files are unsaved, one file is fully marked with "+".

Could you please have a look?
Thank you.

BR

**Comment by pnedev** [comment] 2017-02-03 09:17
Hello Yaron,

I couldn't reproduce the STR under Wine.
Is it steadily reproducable on your side?
What is the CP commit ID you are testing?

Thanks for reporting.

BR

**Comment by Yaron10** [comment] 2017-02-03 23:57
Hello Pavel,

I've tested it with c574eb0 and it's consistent.

It seems to be a recent regression.
I have an old DLL from 25/11/2016 with which the problem does not occur.

I thought it might be caused by my build or my NPP. I've tested it with the DLL you uploaded in https://github.com/pnedev/compare-plugin/issues/89#issuecomment-276371463 and a fresh portable NPP. The same result.

If you have 4 files open, the behavior is even stranger: the third and fourth files get compared.

Thank you very much.
BR

**Comment by Yaron10** [comment] 2017-02-04 05:36
Hello Pavel,

Do you have the option "Re-Compare on Save" checked? - I do. :)
And, obviously, there's also a problem when comparing two different unsaved files and manually closing (one of) them.

Thanks again.
BR

**Comment by pnedev** [comment] 2017-02-06 11:41
Hello Yaron,

I see. You are saying "_Yes_" to the "_Save unsaved file_" question and you have "Re-Compare on Save" enabled.
That is a good catch, thank you :+1: 

BR

**Comment by pnedev** [comment] 2017-02-06 12:53
Hello Yaron,

The issue is fixed in https://github.com/pnedev/compare-plugin/commit/9eba764c8d899dfe8dca37c9f09b659e8bf8f120.
Thanks.

BR

**Comment by Yaron10** [comment] 2017-02-07 01:03
Hello Pavel,

Great work. 👍
Thank you very much.

Some issues with Save All.

**STR 1:**
Have two unsaved files open.
Compare.
Activate the *main-view*.
Save All.

Result:
The sub-view is activated.

**STR 2:**
Have two unsaved files open.
Compare.
Activate the *sub-view*.
Save All.

Result:
No re-Compare.

**STR 3:**
Have four unsaved files open.
Compare A to B and C to D.
Activate A in the main-view.
Save All.

Result:
Not all files are saved and some other "wrongs" :).

Could you please try the last case with ![these](https://cloud.githubusercontent.com/assets/10229320/22672922/964fb50a-ecdf-11e6-86b2-04617578733e.png) four files? (Still a problem with ZIP).

While testing the case with those files, I got the following exception:

![image](https://cloud.githubusercontent.com/assets/10229320/22673011/2aa154ac-ece0-11e6-9d3c-bd76389ca627.png)

When I reported a crash some month ago, it was also with those files (perhaps slightly modified; comparing and re-comparing).
This time NPP did not crash.

Thanks again.
BR

**Comment by pnedev** [comment] 2017-02-07 14:14
Hello Yaron,

I reproduced STR1 and STR2 and now trying STR3.
Thanks for reporting I'll have a look soon.

> While testing the case with those files, I got the following exception:
> This time NPP did not crash.

This is normal CP exception handling. It appears not enough memory was available to CP so it gave error message. There is nothing I can do about that but the good thing is that it doesn't hurt stability at all because the exception was handled by CP. The user can close some files and do the compares pair-by-pair in order not to exhaust the available memory.

BR

**Comment by Yaron10** [comment] 2017-02-07 16:11
Hello Pavel,

Thank you for looking into it. I appreciate that.

> It appears not enough memory was available to CP

I have 4 GB RAM and not many other apps were running at the time. Is that expected? 

> but the good thing is that it doesn't hurt stability at all because the exception was handled by CP.

Indeed. I thought so too.

Please don't mind this minor comment:
"Re-Compare on Save" (capital S) like "Diff since last Save". :)

BR

**Comment by pnedev** [comment] 2017-02-08 08:59
Hello Yaron,

> I have 4 GB RAM and not many other apps were running at the time. Is that expected?

It is certainly something I didn't expect but obviously it is happening. This is what the C++ library gives as fail cause when I try to allocate more memory on the heap. I'll need to investigate further.

> Please don't mind this minor comment:
"Re-Compare on Save" (capital S) like "Diff since last Save".

Good point, thanks.

BR

**Comment by pnedev** [comment] 2017-02-08 09:19
Hello Yaron,

> "Re-Compare on Save" (capital S) like "Diff since last Save".

I've just looked at it. Do you mean the "Re-Compare on Save" in the Settings dialog?
All settings names are with sentence case - "Wrap around diffs", "Compact navigation bar", etc...
"Re-Compare on Save" would be inconsistent there unless I change all strings.

Thanks.

BR

**Comment by pnedev** [comment] 2017-02-08 10:02
Hello Yaron,

> This is what the C++ library gives as fail cause when I try to allocate more memory on the heap. I'll need to investigate further.

The heap memory size available to CP is actually the N++'s heap size. It appears this size is 1MB (at least according to what I've read about the subject) and that's why it gets exhausted so easily when comparing large files. The heap size cannot be increased from CP - it can be done only when compiling N++ (by using a build time linker option).

BR

**Comment by pnedev** [comment] 2017-02-08 12:42
Hello again Yaron,

FYI:
My tests under Wine show that the available heap allocation size is actually 1GB.
Perhaps it is because I'm compiling my changes using MinGW cross-compiler.
I need to check using VS and under native Windows.

BR

**Comment by Yaron10** [comment] 2017-02-08 18:15
Hello Pavel,

> It is certainly something I didn't expect but obviously it is happening. This is what the C++ library gives as fail cause when I try to allocate more memory on the heap. I'll need to investigate further.

Thank you very much for investigating it.
Did you get the exception too?

> I've just looked at it. Do you mean the "Re-Compare on Save" in the Settings dialog?
> All settings names are with sentence case - "Wrap around diffs", "Compact navigation bar", etc...
> "Re-Compare on Save" would be inconsistent there unless I change all strings.

Good point.

Settings:
In "save" you refer to the command "Save" and therefore it should be indeed "Save".
As to "Re-Compare" or "Re-compare" - I tend to think that "Re-Compare" would be better (you refer to the command). And "Go to first diff after re-Compare".
However, I think that "Single-view default compare to" is fine.
"Wrap around diffs" is fine. The "D" in "Diff since last Save" is capital due to its position at the beginning of the sentence. 
And perhaps "Compact Navigation Bar" would be better.

Menu:
"Clear active Compare" and "Clear all Compares" might be better. I'm not sure.

Thank you for that too.

BR

**Comment by pnedev** [comment] 2017-02-09 12:45
Hello Yaron,

> Did you get the exception too?

No, but I still haven't had the chance to test on native Windows.

I have changed the commands and settings names the way you suggest. Thanks.

BR

**Comment by pnedev** [comment] 2017-02-09 13:32
Hello Yaron,

> I have changed the commands and settings names the way you suggest. Thanks.

The command names look OK but the settings dialog is kind-of inconsistent now. At least it looks not quite regular in terms of styling now.
What do you think?

BR

**Comment by Yaron10** [comment] 2017-02-10 00:48
Hello Pavel,

I think it looks fine.
These cAsE rules do not exist in my native language and I don't fully master them. 
Your understanding/impression might be better than mine.

Does the "Save" "bother" you too?

Thank you very much.
BR

**Comment by pnedev** [comment] 2017-02-10 09:52
Hello Yaron,

It is something minor and not important to me. It is a matter of personal preference as I see it - no strict rules apply so both will do - let's keep it this way, thanks.

BR

**Comment by Yaron10** [comment] 2017-02-10 16:01
Hello Pavel,

Great.
Thanks again.

BR

**Comment by pnedev** [comment] 2017-02-15 08:06
Hello Yaron,

The "Save All" behavior is fixed in https://github.com/pnedev/compare-plugin/commit/d21dbe808f20c8723680a5e337f51aecf56dfd5a.
Please have in mind that only the active compare (if any) is re-compared on save. I have changed the name of the user setting respectively.
I'm closing this issue but I'll check the insufficient memory issue and write back in the discussion thread.
Thanks.

BR

**Closed by pnedev** 2017-02-15 08:06 UTC
Labels: bug

**Comment by Yaron10** [comment] 2017-02-16 16:55
Hello Pavel,

It works like a charm.
I think that re-comparing only the active pair on Save All is actually better regardless of the above issues. 👍 

**

Could the memory issue affect the time required for comparing very large files?
In WinMerge such files are compared instantly and, I'm sure, your algorithm is better.

**

Allow me to return to the not-important case question. Sorry.
Seeing it implemented, "Clear Active Compare" and "Clear All Compares" seem better.
What do you think?

**

Great work as always.
Thank you very much.

BR

**Comment by pnedev** [comment] 2017-02-17 08:59
Hello Yaron,

> Could the memory issue affect the time required for comparing very large files?
In WinMerge such files are compared instantly and, I'm sure, your algorithm is better.

No, the memory issue has nothing to do with the time in that case. It just doesn't allow VERY large files to be compared that's all.
Perhaps you'll be surprised to know that actually the most time consuming action during compare is the results presentation phase (the colorization phase) and the blank lines insertion (the alignment).
That's why the files you sent me to illustrate the memory problem are comparing so slowly - due to the many diffs and alignment blank lines.
The next time consuming phase (but considerably less than the first one) is the reading of the files.
The compare itself is pretty fast. The algorithm is really doing a great job but it's not really "my algorithm" - I have just improved it a bit. Thanks :)
WinMerge doesn't have that speed problem because it is a program dedicated to comparing - it directly has the files buffers to compare and does its own dedicated result representation (which is optimized for that purpose). CP relies on Scintilla provided features (those are just GREAT by the way) to present the compare results but those are not aimed at aligning and marking a big portions of the text.

> Seeing it implemented, "Clear Active Compare" and "Clear All Compares" seem better.

So be it :)
Thanks.

BR

**Comment by Yaron10** [comment] 2017-02-17 21:41
Hello Pavel,

Thank you for the detailed and interesting explanation. I appreciate it.
And thanks also for the "So be it". :)

BR
