### ISSUE TITLE
Multi-row tabs not restored after clearing all compares

### ISSUE THREAD

**Issue by jay** [pnedev/compare-plugin#123] opened 2017-03-10 03:42 UTC
Using ComparePlugin.Win32.Debug Unicode.v140_xp 51f0a00.dll

To reproduce:
- Multi-row (Multi-line) tabs enabled
- Split the window into two vertical panes
- Open enough files in one pane to get multiple rows
- Open at least one file in another pane
- Compare > Compare (ie compare the two files that are visible)
- Observe multi-row of tabs has been converted to a single row.
- Open more files
- Compare > Clear All Compares
- Observe multi-row of tabs is not restored.
- Settings > Preferences > General
- Observe 'Multi-line' is checked
- Uncheck it and then check it
- Observe 'Multi-line' is checked, multi-row of tabs is restored

**Comment by pnedev** [comment] 2017-03-10 07:47
Hello @jay ,

Thanks for reporting.
I'm currently busy with a major alignment rework that will affect a lot of things.
I'll look into this issue some time soon.

BR

**Comment by pnedev** [comment] 2017-10-17 10:45
Hello @jay ,

The issue is fixed with commit https://github.com/pnedev/compare-plugin/commit/5458ca6457845cb0acc8897d42c8629813d301eb.

These are the binaries:
- x86: https://ci.appveyor.com/api/buildjobs/gcux44186prs98c9/artifacts/ComparePlugin.dll
- x64: https://ci.appveyor.com/api/buildjobs/e928s4b6s5lq6c16/artifacts/ComparePlugin.dll

Thanks.

BR

**Closed by pnedev** 2017-10-17 10:45 UTC
Labels: bug, question
