### ISSUE TITLE
Recent changes

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#220] opened 2020-01-13 20:09 UTC
Hello Pavel,

Thank you for the detailed and well explained reply.

> If you hold Ctrl key while clicking the margin...

Brilliant. I was impressed.
Now that you process margin-clicks, it might be easier to implement in the future "Go to other Moved-block" on double-clicking a Moved icon.

> I have also made it multi-threaded...
I have also made re-compares more visually appealing...
,,, this will also be indicated in the status bar.

Great.
The Compare is much faster now and the Progress window is hardly visible with medium-size files.

> About #141 I haven't decided yet.
...
I will try to find some viable solution before the release.

:+1:  
***
Can you please compare the [prefs files](https://github.com/pnedev/compare-plugin/files/4055467/prefs.zip) and the [CSS files](https://github.com/pnedev/compare-plugin/files/4055470/userChrome.zip)?
With the recent changes (Build 478), there's a wrong section in the prefs files.
Before the recent changes, there's a wrong section in the CSS files.

Build 478: lines 101-105 should be paired/aligned. 
![תמונה](https://user-images.githubusercontent.com/10229320/72285487-e0315d00-364b-11ea-8437-646011eb5129.png)

Older CopmparePlus: lines 101-105 are correctly paired/aligned.
![תמונה](https://user-images.githubusercontent.com/10229320/72285716-5cc43b80-364c-11ea-9d82-ec9126e4d713.png)

Build 478: lines 47-55 are correctly paired/aligned.
![תמונה](https://user-images.githubusercontent.com/10229320/72285883-b3ca1080-364c-11ea-9d7d-606b652b2783.png)

Older CopmparePlus: those line seem wrong.
![תמונה](https://user-images.githubusercontent.com/10229320/72286128-305cef00-364d-11ea-9e0d-a9c906c607ec.png)
***
As much as I've tried I haven't been able to reproduce the following issue "on demand".
But I've encountered it quite a few times.

Switching between the compared files (click in the other file's editor) might trigger a re-compare.
If I remember correctly it may happen even if Auto re-Compare is disabled. 
***
Set as First to Compare is still defaulted to "New" (after my wrong suggestion in the issue).
***

Whenever you have time to explore and reply.

Thank you.
BR

**Comment by pnedev** [comment] 2020-01-14 09:24
Hello Yaron,

Thank you for the feedback and for the prompt reply (as always). I appreciate it.
I'm also glad that you like the new changes.

> Now that you process margin-clicks ...

That's true but I'll leave it for future versions.

> The Compare is much faster now and the Progress window is hardly visible with medium-size files.

It is the case for most of the usual files, yes. For one or two I tried it is the opposite but those were very specific files. It is connected with the new change detection algorithm.

> Can you please compare the prefs files and the CSS files?

That is an illustration of what I was talking about. The differences are again due to the new change detection algorithm. I wouldn't call any of the results "wrong" - some are more accurate than the others. It is not possible (or at least I haven't come to such universal approach) to be correct in all the cases. One solution is better in one cases, another - in other ones.
It all depends on the criterion used for better change detection - in one case it is the characters count that differ and in the other - the minimum diffs count.
For example you can enable `Detect diffs on character level` in the new CP and re-compare the prefs - the result will be as expected. The old Compare v2 is doing a pretty good job with this files BTW.
But if you try these files ([settings.zip](https://github.com/pnedev/compare-plugin/files/4058256/settings.zip)) with Compare v2 and the new CP you'll see the difference.

I'll think more in the future how to make the change more universal, covering more cases in the "correct" way.

> As much as I've tried ...

I have seen it as well. I haven't found the cause but I also haven't seen it after the latest changes.
Please write if you trigger it again when you are using CP.

> Set as First to Compare is still defaulted to "New" (after my wrong suggestion in the issue).

That's not a problem IMO. Let's leave it that way.

-----------------------------------------------------------------

There are some issues in the development version that I'm fixing in the moment.
Navigation doesn't work in some cases (when caret is not moved and you have annotation occupying the whole screen page) and also sometimes it wraps around when it is disabled.
Margin clicks + `Ctrl` is not OK when doing selection compares. Sometimes when the last diff is "equalized" this way and the compare is automatically closed (which is OK) the change is actually not equalized (the diff is only deleted). Also, not the correct diffs are picked on occasions when only the diffs are shown.
Just letting you know that I know about them :)

I will write again to let you know when I have done my checks and consider things working OK.
Thanks once again.

BR,
Pavel

**Comment by Yaron10** [comment] 2020-01-14 21:18
Hello Pavel,

Sorry for using the term "wrong". "more accurate" is indeed better.

I think the criterion for "more accurate" is how a human would pair the lines.
And surely we would pair the `user_pref("extensions.blocklist.lastModified"` lines (101) and mark them as Changed.

I don't know anything about the "under the hood" mechanism and this a long shot: 
Would it be very complex to let the user choose between "Compare Method 1" and "Compare Method 2"?
So in cases where it's obvious that one method is not optimal, the user would try the other one.
-- Yes, it's easy to come up with suggestions. :)
***
> I have seen it as well...
...
That's not a problem IMO. Let's leave it that way.

:+1: 
***
> There are some issues in the development version that I'm fixing in the moment...

Thank you and best of luck.
These WIP features look great. The same is true regarding the new first line approach.
I'll be waiting for your "Ready, Go".

Should I close this issue?

Much appreciated.
BR

**Comment by pnedev** [comment] 2020-01-15 07:55
Hello Yaron,

> Sorry for using the term "wrong"

No problem at all. I just wanted to point out that each approach is good in some cases and not good (accurate) in others.
I agree with you.

> Would it be very complex to let the user choose between "Compare Method 1" and "Compare Method 2"?

I'll consider adding such setting.

Let's leave this thread open for now, I'll use it to update you on the status.
Thank you.

BR

**Comment by Yaron10** [comment] 2020-01-15 22:24
Hello Pavel,

:+1: 
Thank you. As always, I appreciate your work.

BR

**Comment by Yaron10** [comment] 2020-02-26 14:03
Hello Pavel,

Despite the recent improvements, I've still been a ComparPlus from about a year ago.

I compare the prefs files quite often and it's more convenient with the old approach.
Comparing now the [files](https://github.com/pnedev/compare-plugin/files/1412340/Test.zip) from https://github.com/pnedev/compare-plugin/issues/141, the old approach seems more accurate (as is the case with other files). 

Older CP.
![תמונה](https://user-images.githubusercontent.com/10229320/75350228-cf147680-58ae-11ea-9aa7-910dfaaa17c3.png)

Latest CP.
![תמונה](https://user-images.githubusercontent.com/10229320/75350291-ea7f8180-58ae-11ea-8e55-6b43b2839ea6.png)

But I don't want to miss the many major improvements. :)

If you haven't decided yet regarding my suggestion "Use Alternative Compare Method", would you mind reverting to the old approach for the time being?
Do you consider the new approach better (all in all)?

Thank you.
BR

**Comment by pnedev** [comment] 2020-02-26 14:56
Hello Yaron,

I suppose I will add an option to switch the changes detection method as you suggested.
Because both are viable in different circumstances.

I'll write back when ready, thank you.

BR

**Comment by pnedev** [comment] 2020-02-26 15:55
Hello again, Yaron,

The last result you are getting is not due to the new changes detection approach.
And the latest CP is "_more correct_" in this comparison, let me explain.
Looking at the lines sequences, line 2931 in file2 is empty line. And it should match the first empty line from file1 following the previous match (the curly braces at lines 2929-2930). The first empty line from file1 is 2932.
So the older CP "_erroneously_" matches the empty lines 2932-2934 while it should match 2932-2931 (as is the case with the latest CP). And this changes the diff blocks that are checked for changed lines.

Shortly put, because the latest CP does better lines sequence match it groups diffs differently leading to this "_worse_" result from changed lines perspective.
To get the old result you'll need to ignore the empty lines matching.

As a remark - Compare v2 gives the same result as the latest CP.

Unfortunately I cannot change that behavior. It is correct from compare perspective, I'm sorry that it is not as visually appealing as the older CP result.

As an illustration you can compare again 
[**these**](https://github.com/pnedev/compare-plugin/files/4256728/Test.zip) slightly modified files - the differently matching empty lines are replaced with matching text.

Tell me if you have any comments, thanks.

BR

**Comment by Yaron10** [comment] 2020-02-26 21:49
Hello Pavel,

Thank you for the detailed explanation. :+1: 

Fully mastering it would require some more thinking.
And the following lines are written without doing so.

I don't have another Diff tool installed; I've compared some files in the following sites:
https://text-compare.com
https://www.diffchecker.com/diff

The `Notepad_plus` files are displayed as they are in the latest ComparePlus.
The `prefs` files are displayed as they are in the *older* ComparePlus. 
The `userChrome` files are displayed as they are in the *latest* ComparePlus.

Can't this be achieved in CP with one compare method? 

If not, I do appreciate the extra setting.
(IMO it should be in the menu. What do you think?).

Anyway, thanks again for your great work.

BR

**Comment by pnedev** [comment] 2020-02-27 15:09
Hello Yaron,

I will add the extra setting for more flexibility.
Perhaps the menu is the right place for it, I'm not sure yet.

I'll write again soon :+1: 

BR

**Comment by Yaron10** [comment] 2020-02-27 21:38
Hello Pavel,

:+1: 
Thanks again. I appreciate it.
Whenever you have time.

BR

**Comment by pnedev** [comment] 2020-03-02 15:04
Hello Yaron,

I have added the new menu setting, here are the binaries:

- [**x86**](https://ci.appveyor.com/api/buildjobs/9h7girw4k3om8rwc/artifacts/ComparePlus.dll)
- [**x64**](https://ci.appveyor.com/api/buildjobs/29kka4j03yyh23op/artifacts/ComparePlus.dll)

By default the new changed lines detection won't be used.
I suppose it will be good if you delete your ComparePlus.ini config file.

BR

**Comment by Yaron10** [comment] 2020-03-03 11:59
Hello Pavel,

Thank you for the latest changes. I do appreciate it.

With the new setting unchecked, the files used in this thread (`prefs`, `userChrome`) are displayed "more accurately".
This is really great. :+1: 

So, what's the purpose of that setting?
Are there other cases where the results are "less accurate" without it?

Now that I can use the latest CP, I'd like to thank you again for fixing the glitches in https://github.com/pnedev/compare-plugin/issues/141 and for the Diff Equalization feature. :+1: 

BR

**Comment by pnedev** [comment] 2020-03-04 00:13
Hello Yaron,

And Thank you. Now I'm really close to releasing the new plugin.

> So, what's the purpose of that setting?
Are there other cases where the results are "less accurate" without it?

Yes, you can try comparing 
[**these**](https://github.com/pnedev/compare-plugin/files/4284295/langs.zip) files with and without the new option.

I will write again soon to let you know when ComparePlus v1 is ready.
Please feel free to write if you come across something that doesn't look right.
Thank you once again for all the help.

BR

**Comment by Yaron10** [comment] 2020-03-04 15:23
Hello Pavel,

Thank you for the `langs` files.

It requires some thinking which may lead to a possibly long discussion. 
If you think that you have fully grasped and exhausted the issue and the current implementation is best, that discussion better be spared.

If further discussing it might be helpful, you'd probably prefer doing it some time in the future after the release of ComparePlus v1.
***
> Please feel free to write if you come across something that doesn't look right.

https://github.com/pnedev/compare-plugin/issues/141#issuecomment-591465384
You probably remember it.

Should the "Re-Compere Selections" issues we've discussed be fixed?
Do you remember the relevant thread?
***
I'm really glad you are about to release ComparePlus v1. Many thanks for your amazing work.
To be continued. :)

BR

**Comment by pnedev** [comment] 2020-03-04 20:24
Hello Yaron,

Let's leave the further discussions about the new changes detection approach for now. Your feedback is more than welcome but I will freeze the changes until ComparePlus v1 is released.
Thank you.

About #141 yes, I remember and I'll fix it before the release. That's why the thread is still open. Thanks for reminding me though.

I can't remember the issues around selections re-compare :(
What were they, are there still any?

I'm currently travelling so I won't be able to comment much till next week.
I'll write again as soon as I can.

BR

**Comment by Yaron10** [comment] 2020-03-05 20:15
Hello Pavel,

> Let's leave the further discussions about the new changes detection approach for now.
...
About #141 yes, I remember and I'll fix it before the release.

:+1: 
Thank you.

> I can't remember the issues around selections re-compare.

Unfortunately I can't find the relevant discussion.
I've opened a [new issue](https://github.com/pnedev/compare-plugin/issues/229).
***
I hope you have a good time.
BR

**Comment by pnedev** [comment] 2020-03-06 08:51
Hello Yaron,

Thanks for opening the new issue.
I'll close this thread now.

BR

**Closed by pnedev** 2020-03-06 08:51 UTC
Labels: enhancement, question
