### ISSUE TITLE
Compare Selected Lines: Some Issues

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#107] opened 2017-02-02 18:37 UTC
Hello Pavel,

STR:
Open two identical files.
Select lines 10-15 in file A (new) and lines 10-20 in file B.
Compare SL.

Result:
Lines 21-25 in file B are blank.

Expected result:
No blank lines in 21-25 (out of range).
***
STR:
In the same files select lines 10-25 and re-Compare SL.
Clear Compare.

Result:
Some blank lines are not removed.

Thank you very much.
BR

**Comment by pnedev** [comment] 2017-02-03 09:07
Hello Yaron,

Thanks for reporting.

The first STR is implemented on purpose. It is done because of the re-compare case. It also equalizes the compared files lengths.

Try this:

1) Compare two different files A and B.
2) Make some selections in A and in B that are before the current last diff (make the selections with different starting line and different lengths).
3) Compare SL.

The added blank lines before one of the selections align the compared sections.
The added blank lines after one of the selections equalize files lengths and align the diffs from the previous compare that remained below the selections.
I know, if we had cleared the old results before selection re-compare that wouldn't be strictly necessary :)

I couldn't reproduce the second STR.
What CP commit ID are you using? I'm currently working exactly on that behavior and frequently change things. I tested with commit https://github.com/pnedev/compare-plugin/commit/c574eb01b101f4f2a47c449747106d5aab72f2d1.

BR

**Comment by Yaron10** [comment] 2017-02-03 23:56
Hello Pavel,

I've also tested it with https://github.com/pnedev/compare-plugin/commit/c574eb01b101f4f2a47c449747106d5aab72f2d1. 
A bit of a mess with this issue and our discussion in https://github.com/pnedev/compare-plugin/issues/89. :)
I've elaborated there.

Thank you very much.
BR

**Comment by pnedev** [comment] 2017-02-06 09:10
Hello Yaron,

This is fixed in https://github.com/pnedev/compare-plugin/commit/4883ac9a86c1b2beb038e8adc4bd43e31684fbe3.

Thank you.

BR

**Closed by pnedev** 2017-02-06 09:10 UTC
Labels: question

**Comment by Yaron10** [comment] 2017-02-07 01:03
Hello Pavel,

Great. 👍 
Thank you very much.

BR
