### ISSUE TITLE
XML compare view automatically scrolls to the end of lines

### ISSUE THREAD

**Issue by giustizieri25** [pnedev/compare-plugin#134] opened 2017-07-06 07:56 UTC
When comparing two XML files side by side, the view on the right side Always places the cursor at the end of each line and scrolls to the far right on every lost focus event (for example if you put focus on the left side comparison panel, or scroll the right side up or down, or change selection, and so on ... ). I Always have to press the home button to bring the XML content in the view again. Would be nice to leave the horizontal scrolling unchanged, when focus changes.

**Comment by pnedev** [comment] 2017-07-06 08:30
I'll keep that in mind for the upcoming new plugin version, thanks for reporting.

BR

**Comment by pnedev** [comment] 2017-10-16 14:51
Hello @giustizieri25 ,

Could you please try again with the latest development plugin version?
That will be very helpful. You can find the latest version at the end of this issue thread: https://github.com/pnedev/compare-plugin/issues/122.

It will behave (and 'feel') differently from version 2.0 because there are a lot of other significant changes in the code but is completely OK to test your issue. It should be resolved but since I haven't reproduced it I'm not able to test it.
Thanks for your help.

BR

**Comment by pnedev** [comment] 2017-10-17 11:20
Hello again,

I did some tests and the file view is preserved (compare plugin shouldn't interfere with the view, it merely synchronizes the views position horizontally and vertically when files are compared).
I'll close this thread now and consider the problem resolved but if you experience the same (or another of course) issue in the future please write back.
Thanks.

BR

**Closed by pnedev** 2017-10-17 11:20 UTC
Labels: question
