### ISSUE TITLE
Multi-line tabs displace text

### ISSUE THREAD

**Issue by ganego** [pnedev/compare-plugin#105] opened 2017-01-14 13:36 UTC
I have several files open at the same time and the multi-line tab option in Notepad++ enabled. So instead of scrolling I always have them on screen in one or two rows.
When 'compare' opens the second window, the tab bar will be narrowed down a lot, making it have more rows. See this screenshot: http://imgur.com/a/thdTN

The easiest solution I see is give the user an option in your plugin, that when the compare plugin compares two files, it sets the npp setting from multi-line tabs to single-line (and of course back after comparing).

Is that possible?
Thank you

**Comment by pnedev** [comment] 2017-01-15 00:55
Hello,

I'll have a look on Monday, thanks.

BR

**Comment by Yaron10** [comment] 2017-01-15 22:49
Hello Pavel and @ganego,

Pavel,
Knowing you, you'd probably reply it's not a CP issue. :) And I'd agree.
If you do consider implementing it, I know you wouldn't like to bloat the Settings window.
How about a "hidden setting"? - Add an entry in the INI file without an extra setting in the Settings window.
I suppose @ganego would find that adequate.

Thank you.
BR

**Comment by pnedev** [comment] 2017-01-16 08:55
Hello Yaron,

I'm becoming predictable, am I not? ;)
Jokes aside, I think that behavior should not be an option at all but should be always on because it would affect the views synchronization for all users that are having vertical views configuration (side-by-side views layout).
I just need some time to see if I can actually do something about it.
Thanks.

BR

**Comment by pnedev** [comment] 2017-01-16 13:38
Hello @ganego and @Yaron10 ,

The multiline tab-bar issue is fixed in commit https://github.com/pnedev/compare-plugin/commit/45238d6a630d0eac1048ff2a3aeb6c0794d4e1ad.
You can find the latest x64 build at 
https://ci.appveyor.com/api/buildjobs/mbbwqw38ybc3ri39/artifacts/ComparePlugin.dll
and the latest x86 build at https://ci.appveyor.com/api/buildjobs/affjyu0nufrsvte5/artifacts/ComparePlugin.dll.

BR

**Comment by Yaron10** [comment] 2017-01-16 18:35
Hello Pavel,

> I'm becoming predictable, am I not?

Your following lines prove you're not. :)

> because it would affect the views synchronization for all users that are having vertical views configuration

I thought about that too and it's a good point.

> I think that behavior should not be an option at all but should be always on

Some users might argue now that "CP breaks my Multi Lines Tab setting". :)
***
Two cases where the window should be (programmatically) refreshed/repainted:
1) On restoring Multi Lines after clearing all compares.
2) If you start NPP with Top/Bottom layout, change to Left/Right and Compare.
***
When switching to Single Line Tab, would it be possible to make the two compared files visible in both Tab bars? IOW: scroll to the compared file.
***
Just curious:
Using `if (mainTabYPos == subTabYPos)` to determine the views layout is very nice.
Did you not use `<GUIConfig name="ScintillaViewsSplitter">horizontal</GUIConfig>` in case the user changes the layout and Compare (i.e. it's not yet saved in config.xml)?
But it must be saved somewhere.

Thank you very much. Great work.
BR

**Comment by pnedev** [comment] 2017-01-17 08:43
Hello Yaron,

> Some users might argue now that "CP breaks my Multi Lines Tab setting".

I prefer to wait to see if that happens and if it does I may add an option about this feature.

> Two cases where the window should be (programmatically) refreshed/repainted:
> On restoring Multi Lines after clearing all compares.
> If you start NPP with Top/Bottom layout, change to Left/Right and Compare.

Yes, You are right. I saw that too on my Linux/Wine setup but I thought it was due to the emulation (it had happened before). Refreshing the window also didn't have any effect under Wine. I'll try on Win7.

> When switching to Single Line Tab, would it be possible to make the two compared files visible in both Tab bars? IOW: scroll to the compared file.

Is it not always scrolled? I haven't noticed that. But I haven't extensively tested either. I'll have a look, thanks.

> Did you not use <GUIConfig name="ScintillaViewsSplitter">horizontal</GUIConfig> in case the user changes the layout and Compare (i.e. it's not yet saved in config.xml)?

I prefer not to rely on N++ config.xml - parsing it will require unnecessary additional coding.
What you are thinking is just a good side effect in my opinion.

Thank you, Yaron.

BR

**Comment by ganego** [comment] 2017-01-17 10:53
Thank you. I installed Build 8 from appveyor yesterday.
>Two cases where the window should be (programmatically) refreshed/repainted:
> On restoring Multi Lines after clearing all compares.

> Is it not always scrolled? I haven't noticed that. But I haven't extensively tested either. I'll have a look, thanks.

Yes those are the two only minor issues left but I didn't want to bother you with them :)
Right now after you close the compare there is only one tab bar line visible, but when you click on one tab it refreshes the UI and all are shown.
And the left tab bar in the compare window, where all the other tabs are is not scrolled to the rightmost tab (=the one getting compared). Not a big deal only polish.

**Comment by Yaron10** [comment] 2017-01-17 17:14
Hello Pavel,

> I prefer to wait to see if that happens and if it does I may add an option about this feature.

👍 

> ...
> I'll try on Win7.

Thank you very much. As always, I appreciate it.

> I prefer not to rely on N++ config.xml - parsing it will require unnecessary additional coding.

Sometimes I have a quick look at short commits. :)
I really liked the clever `if (mainTabYPos == subTabYPos)` idea.
Thanks for the explanation.
***
Hello @ganego,

> Yes those are the two only minor issues left but I didn't want to bother you with them

That's kind of you.
I just assume Pavel would like to get feedback to his (excellent) work. Informative and, obviously, positive. :)

Thank you.
***
Best regards.

**Comment by pnedev** [comment] 2017-01-18 08:32
Hello @ganego  and @Yaron10 ,

Thank you both for the feedback, I'll look into those issues soon.

BR

**Comment by pnedev** [comment] 2017-01-19 09:19
Hello @ganego  and @Yaron10 ,

Could you please try commit https://github.com/pnedev/compare-plugin/commit/3d38e8280a764ef9d6f7946e7c0d9deccc981596?

The binaries are here:

- x64: https://ci.appveyor.com/api/buildjobs/de87pev57mghh4yt/artifacts/ComparePlugin.dll
- x86: https://ci.appveyor.com/api/buildjobs/gvrpbnxj4rhww45k/artifacts/ComparePlugin.dll

Thanks.

BR

**Comment by ganego** [comment] 2017-01-19 11:27
The refresh works fine, thank you.

The scrolling in the left window (where all tabs are) does not work perfectly (but ok).
Example: http://imgur.com/a/fsuo2
The exact position depends on the number of tabs, but in all cases if you could emulate like one click on the ">" button, it would always fit.
But this might be only an issue because I use the DPI zoom (Display Scaling) in Windows 7 - does it work for you @Yaron10?

**Comment by Yaron10** [comment] 2017-01-19 16:46
Hello Pavel,

Thank you for fixing these issues. I appreciate your work. 👍 
Everything works properly on my machine.

Hello ganego,

I use 100% DPI on Windows 7.
I've tried to reproduce the problem shown in your image but to no avail.
Could you please try it with a different NPP window width?
Pavel may have another idea.

Best regards.

**Comment by ganego** [comment] 2017-01-19 16:57
>  Could you please try it with a different NPP window width?
Same behavior, no matter what width the NPP window has (well with some certain widths it works by accident).
I cannot test different DPI scalings because I'd have to log out from my windows account and this is not possible at the moment.

**Comment by Yaron10** [comment] 2017-01-19 18:47
Hello,

> well with some certain widths it works by accident

This may be important.
Let's wait for Pavel.
***
Pavel,

I've just come across another minor issue:
Multi Lines Tab is not restored after using "Clear all Compares".

Thank you.
BR

**Comment by pnedev** [comment] 2017-01-19 22:27
Hello guys,

I have only a vague idea.
I was able to reproduce the issue. The active tab is partially visible. 
Another problem is that the mouse scroll function does not work, only the arrow buttons. It seems as if the tab bar is not considered to be scroll-able.
Thank you for testing. I'll see if I can do something about those issues.

@Yaron10 ,

Thanks for catching the "Clear all Compares" case - I'll have a look at it tomorrow.

BR

**Comment by Yaron10** [comment] 2017-01-19 23:29
Hello Pavel,

> I was able to reproduce the issue. The active tab is partially visible.

Is it indeed DPI related?

> Another problem is that the mouse scroll function does not work, only the arrow buttons. It seems as if the tab bar is not considered to be scroll-able.

Do you mean Ctrl + Wheel?
It works for me.

Thank you very much.
BR

**Comment by ganego** [comment] 2017-01-20 09:44
> Do you mean Ctrl + Wheel?
> It works for me.

Also works for me.

**Comment by pnedev** [comment] 2017-01-20 10:16
Hello guys,

Sorry for my brief previous message - it is indeed not very specific about the mouse wheel problem but I didn't have much time yesterday.

When you are not using multiline tab bars (configured in N++ settings that is) then when you have many tabs and you position the mouse cursor over one of them you can use the mouse wheel to scroll the tabs list left and right.
This is the feature that was also not working when I was switching to single line tab bar on compare.
This is connected to the partially visible active tab problem.

It appears N++ handles tab bar scrolling by itself - it detects if the tab is partially visible (which seems the normal Win32 Tab Control behavior) and also handles mouse wheel scrolling. The problem is that N++ keeps internal state of the multiline tab bar settings and when I change it from outside it doesn't know about that. That's why it does not handle the scrolling - it thinks tab bars are still multiline.

I have fixed all those issues and the issue with "Clear all Compares" that Yaron reported.
Here is the commit: https://github.com/pnedev/compare-plugin/commit/a446b90884274f90c5da689b5867765ab545044e

The corresponding binaries are:

- x64: https://ci.appveyor.com/api/buildjobs/y61t9m4cfe94i404/artifacts/ComparePlugin.dll

- x86: https://ci.appveyor.com/api/buildjobs/ma9df0tnxoayvykt/artifacts/ComparePlugin.dll

Please test and write back, thank you.

BR

**Comment by ganego** [comment] 2017-01-20 11:45
With this version mousewheelscrolling without CTRL works fine.
But now the tab bar is again at the leftmost tab (so the first tab is visible on the left side of the screen).
In the previous version, where scrolling only worked with ctrl, the tab bar was scrolled to the rightmost tab (well with the issue above, that the last tab was not completely visible). So (besides scrolling) it was better before.
Maybe you could fix the bug where the last tab is not completely visible by just calling the function that the ">" button uses like 10 times or so? Probably not the most elegant solution but should work (I think).

**Comment by pnedev** [comment] 2017-01-20 12:40
OK, got it.

In the following binaries the problem should be fixed:

- x64: https://ci.appveyor.com/api/buildjobs/76labjggl914ffdt/artifacts/ComparePlugin.dll

- x86: https://ci.appveyor.com/api/buildjobs/p5vsue8bqv0u4dvw/artifacts/ComparePlugin.dll

BR

**Comment by ganego** [comment] 2017-01-20 15:02
Yes, now it goes to the last tab like before.

**Comment by Yaron10** [comment] 2017-01-20 15:38
Hello Pavel,

> When you are not using multiline tab bars...

Thanks for the clarification.
I didn't know (or didn't remember) you could scroll without Ctrl in Single Line Tab.

> I have fixed those issues and the issue with "Clear all Compares" that Yaron reported.

Great. 👍 
***
I wonder why I wasn't able to reproduce the "partially visible tab" issue.
Could you please provide more specific STR?

Thank you very much. Highly appreciated.
BR

**Comment by ganego** [comment] 2017-01-20 17:12
@Yaron10 did you change DPI scaling? I have it at 125%.

**Comment by Yaron10** [comment] 2017-01-20 20:08
I was able to reproduce it with 125%. I had to play quite some time with the window width.
I thought Pavel reproduced it regardless of the DPI. 

Anyway, all is well now. :)
Thank you. 
And thank you Pavel for your great work.

BR

**Comment by pnedev** [comment] 2017-01-21 12:33
Hello Yaron,

I won't be around my computer till Tuesday but if I remember correctly my DPI setting is also 125%. Perhaps that's why the issue appeared instantly (I didn't have to do anything specific to trigger it).

BR

**Closed by pnedev** 2017-01-21 12:33 UTC
Labels: enhancement

**Comment by Yaron10** [comment] 2017-01-21 15:46
Thank you Pavel.
BR
