### ISSUE TITLE
Compare Selected Lines: Make sure the first *non-blank* line is visible

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#142] opened 2017-10-24 22:27 UTC
Hello Pavel,

STR:
Use the files uploaded in https://github.com/pnedev/compare-plugin/issues/141#issue-268207643.
Select lines 355-361 in Notepad_plus Old.cpp and lines 250-254 in Notepad_plus New.cpp.
Compare Selected Lines. 
Select the same lines again.
Activate Notepad_plus Old.cpp.
Compare Selected Lines.

Result:
The first *non-blank* line is not visible.

The issue can probably be reproduced in other shorter cases. :)
In general it seems that Compare Selected Lines is implemented better in v3 (regarding the visibility of "real lines").
Still, it would be great if you could look into it.

Thank you.
BR

**Comment by pnedev** [comment] 2017-10-25 08:38
Hello Yaron,

I know that currently when you compare/re-compare or visit some compared locations the expected lines sometimes go out of scope (are not in view) and I'm trying to find a suitable way to fix that.

But could you try your scenario with the last binary (the one from https://github.com/pnedev/compare-plugin/issues/108)?
I failed to reproduce it but I'm sure the issue you describe is connected to the things I'm trying to fix.

Thanks.

BR

**Comment by Yaron10** [comment] 2017-10-25 17:55
Hello Pavel,

Fixed with the last binary. 👍 
I appreciate your excellent work.

Should I close this issue or leave it open for further tests?

BR

**Comment by pnedev** [comment] 2017-10-26 08:00
Hello Yaron,

OK, good.
I'll close this thread as the problem is tracked in https://github.com/pnedev/compare-plugin/issues/141.
Thanks.

BR

**Closed by pnedev** 2017-10-26 08:00 UTC
Labels: question
