### ISSUE TITLE
Mouse-Scroll doesn't work if a side bar is open

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#31] opened 2016-03-26 01:45 UTC
Hello Pavel,

STR:

Start NPP.
Open two files.
Open NPP Function List.
Compare.

Result:
Mouse-Scroll over either view doesn't work until pressing somewhere in the editor.

NOTE:
It seems the problem only occurs after the first Compare.
It works properly if you Clear Results and compare again.

Thank you.

**Comment by pnedev** [comment] 2016-03-27 01:34
Will check that, thanks for reporting.

BR

**Comment by Yaron10** [comment] 2016-03-27 21:00
Thank you Pavel. I appreciate it.

BR

**Comment by pnedev** [comment] 2016-04-06 11:42
Cannot reproduce that on latest master branch commit.
I will close that now, please reopen it if you are still having that issue, thanks.

BR

**Comment by Yaron10** [comment] 2016-04-08 14:37
Hello Pavel,

> NOTE:
> It seems the problem only occurs after the first Compare.
> It works properly if you Clear Results and compare again.

Still reproducible.
IMO it can be marked as a minor known issue.

Thank you.

**Comment by pnedev** [comment] 2016-04-12 16:24
Hello Yaron,

I'm still unable to reproduce that with the latest master branch code.
I'm trying this on Linux under Wine, my Npp version is 6.9.1.
What is yours?

I'll try on my Win7 machine later.

BR

**Comment by pnedev** [comment] 2016-04-12 23:03
The issue is reproducible on my Win7 machine. I'll have a look at it later, thanks.

BR

**Comment by Yaron10** [comment] 2016-04-13 02:53
Great (is it? :) ).

Thank you.
BR

**Comment by pnedev** [comment] 2016-04-23 00:10
Fixed in master, thanks,

BR

**Closed by pnedev** 2016-04-23 00:10 UTC
Labels: bug

**Comment by Yaron10** [comment] 2016-04-23 22:23
Thank you very much.
BR
