### ISSUE TITLE
HEX lines are falsely considered matching

### ISSUE THREAD

**Issue by tsurrdurr** [pnedev/compare-plugin#128] opened 2017-05-13 16:58 UTC
I used different versions of Notepad++ 32-bit on windows but mostly 7.3.3 and Compare 2.0 plugin installed from NPP plugin manager.
I have a file in left view and a file in right view and compare them with Plugins > Compare > Compare.
The lines format is [Intel HEX](https://en.wikipedia.org/wiki/Intel_HEX).
When i compare two files with lines in different views looking as following:
`:100400000100000040F2010CC2F2010C604740F212`
`:100400000000000040F2010CC2F2010C604740F213`
The lines are considered matching and don't get highlighted. If files only contain these lines, they are pronounced as matching as well. If such lines are typed in a column, they all "match".
I managed to reproduce it on examples like:
`:100400000300000040F2010CC2F2010C604750F200`
`:100400000000000040F2010CC2F2010C604750F203`
and
`:1004000002000000000000000000000000000000EA`
`:1004000000000000000000000000000000000000EC`
However, it finds differences correctly with lines of another length, if lines differ in other positions and if checksum consists of a letter and a numeral. I haven't yet found any other specific cases of bug reproduction.

**Comment by pnedev** [comment] 2017-05-15 07:53
Hello @tsurrdurr ,

Thanks for the issue report.
I can reproduce the problem thanks to your detailed explanation and I'll investigate it but it might take time as I'm in the middle of a major plugin rework.
I'll write again when I get to this.

BR

**Comment by pnedev** [comment] 2017-05-17 07:25
Hello @tsurrdurr ,

FYI:
The issue is coming from the compare hashing function - it produces the same hash value for every pair of your example strings. I have fixed that in my current development version and the fix will be in the next version of CP but I still have several issues to deal with (due to the refactoring) before the release.

Thanks for reporting the problem.

BR

**Comment by Yaron10** [comment] 2017-05-17 18:56
Hello Pavel,

I hope you're doing well.
Thank you for your ongoing work. :)

Best regards.

**Comment by pnedev** [comment] 2017-05-18 07:17
Hello @Yaron10 ,

I'm fine, thank you.
I hope you are OK as well. :)

Best Regards

**Comment by pnedev** [comment] 2017-10-16 14:43
Hello,

The fix for the issue is included in the latest master branch updates, please have a look at this issue: https://github.com/pnedev/compare-plugin/issues/122.

It will be officially available in the new plugin release, thanks.

BR

**Closed by pnedev** 2017-10-16 14:43 UTC
Labels: bug
