### ISSUE TITLE
Add the Option "Show only Differences"

### ISSUE THREAD

**Issue by VasanthapuramMahesh** [pnedev/compare-plugin#203] opened 2019-05-23 11:31 UTC
I need this feature. When select this option only shows modified ones.

**Comment by pnedev** [comment] 2019-05-23 11:44
Duplicate of [**this**](https://github.com/pnedev/compare-plugin/issues/185) issue.
It is implemented in the current development build that is to be released some time in the near future.

**Closed by pnedev** 2019-05-23 11:44 UTC
